Module Action
Program flame
Version 2011.1.SP3
FileVersion 2
CreationDate Mon Mar 21 18:01:59 2011

FrameWidth 2048
FrameHeight 1556
FramePixelFormat 131
FrameAspectRatio 2.630000114
FrameDominance 2

	MinFrame 1
	CurrentFrame 200
	MaxFrames 200
	ShadingMode no
	WireframeMode no
	ZBufferMode yes
	FilteringDefault Linear
	FilteringQuality Interactive
	LinetestMode no
	MultiSample 0
	CurrentCamera 17
	GridMode 3
	Grid3DColour 0.3 0.3 0.3
	CameraPlaneType 0
	PlayLockMode no
	BackupMode yes
	BackupTime 30
	QuickResolution 6
	AntiAliasingLevel 0
	AntiAliasingSoftness 1
	MotionBlurEditor
		Channel 
			Extrapolation constant
			Value 1
			Size 3
			KeyVersion 1
			Key 0
				Frame 50
				Value 1
				FrameLock yes
				DeleteLock yes
				Interpolation hermite
				End
			Key 1
				Frame 100
				Value 1
				Interpolation hermite
				End
			Key 2
				Frame 150
				Value 1
				FrameLock yes
				DeleteLock yes
				Interpolation hermite
				End
			End
		ChannelEnd
	TopLevelChannel
		Channel scene
			Uncollapsed
			End
	ResultCamChannel
		Channel ResultCamera
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		ChannelEnd
MotionBlurTopChannel
		Channel motion_blur
			Uncollapsed
			End
		MotionBlurPhaseChannel
		Channel phase
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		ChannelEnd
	MotionBlurEnableChannel
		Channel enable
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		ChannelEnd
	MotionBlurShutterChannel
		Channel shutter
			Extrapolation constant
			Value 1
			Uncollapsed
			End
		ChannelEnd
	MotionBlurSamplesChannel
		Channel samples
			Extrapolation constant
			Value 5
			Uncollapsed
			End
		ChannelEnd
		DofMode no
		DofSoftness 1
		FogMode Off
		FogColour 0 0 0
		FogStart 0
		FogEnd 1
		FogRange 1
		ProjectorMotionPathMode no
		CamMotionPathMode no
		AxisMotionPathMode no
		LightMotionPathMode no
		PropScalingMode no
		SPropScalingMode yes
		YSnapMode no
		YGridSize 1
		AutoKeyMode yes
		UpdateMode yes
		AutoParentMode yes
		ForceProxyUpdate yes
		UndoLevels 10
		DrawIconsMode IconsOn
		IconTransparency 0
		SchematicTransparency 0
		ClipInfo 0
		SubMenu AXIS_MENU
		ColourClamping no
		End

#
# node database
#
ConcreteFileVersion 1.5
CreationDate Mon Mar 21 18:01:59 2011


WorldScale 1

Node Group
	Name scene
	Number 0
	Child 1
	Child 2
	Child 3
	MotionPath no
	PosX 0
	PosY 0
	Flags SCHEMATIC_HIDDEN
	OutputsSize 1
	0
	Specifics
	{
	}
End
Node Camera
	Name DefaultCam
	Number 1
	MotionPath no
	PosX -530
	PosY 258
	OutputsSize 0
	Specifics
	{
		CamChannel
		{
		Channel position/x
			Extrapolation constant
			Value 0.000000000
			End
		Channel position/y
			Extrapolation constant
			Value 0.000000000
			End
		Channel position/z
			Extrapolation constant
			Value 2137.537109375
			End
		Channel speed
			Extrapolation constant
			Value 0
			End
		Channel interest/x
			Extrapolation constant
			Value 0.000000000
			End
		Channel interest/y
			Extrapolation constant
			Value 0.000000000
			End
		Channel interest/z
			Extrapolation constant
			Value 0.000000000
			End
		Channel int_speed
			Extrapolation constant
			Value 0
			End
		Channel rotation/x
			Extrapolation constant
			Value 0.000000000
			End
		Channel rotation/y
			Extrapolation constant
			Value 0.000000000
			End
		Channel rotation/z
			Extrapolation constant
			Value 0.000000000
			End
		Channel roll
			Extrapolation constant
			Value 0.000000000
			End
		Channel fov
			Extrapolation constant
			Value 40.000000000
			End
		Channel near
			Extrapolation constant
			Value 1
			End
		Channel far
			Extrapolation constant
			Value 10000
			End
		Channel distance
			Extrapolation constant
			Value 2137.54
			End
		Channel lens_distortion/x
			Extrapolation constant
			Value 0
			End
		Channel lens_distortion/y
			Extrapolation constant
			Value 0
			End
		Channel lens_distortion/magnitude
			Extrapolation constant
			Value 0
			End
		Channel lens_distortion/adjustment
			Extrapolation constant
			Value 0
			End
		Channel lens_distortion/anamorph
			Extrapolation constant
			Value 1
			End
		ChannelEnd
		}
		CamLensFitRes 0
		CamLensFilter 1
		CamLensMode 0
		CamMotionPathMode no
		CamMotionPath
		{
		Path pos_path
			Dimension 3
			Closed no
			Size 0
			End

		Path poi_path
			Dimension 3
			Closed no
			Size 0
			End

		}
		Origin 0
		CamIndex 0
		CamPhysicalParameters
		PhysicalCameraEnabled no
		FStop FStop_1
		Film_Type 35mm_Full_Frame
	}
End
Node Camera
	Name WorkingCam
	Number 2
	MotionPath no
	PosX -394
	PosY 258
	Flags HIDDEN&SCHEMATIC_HIDDEN
	OutputsSize 0
	Specifics
	{
		CamChannel
		{
		Channel position/x
			Extrapolation constant
			Value 0.000000000
			End
		Channel position/y
			Extrapolation constant
			Value 0.000000000
			End
		Channel position/z
			Extrapolation constant
			Value 2137.537109375
			End
		Channel speed
			Extrapolation constant
			Value 0
			End
		Channel interest/x
			Extrapolation constant
			Value 0.000000000
			End
		Channel interest/y
			Extrapolation constant
			Value 0.000000000
			End
		Channel interest/z
			Extrapolation constant
			Value 0.000000000
			End
		Channel int_speed
			Extrapolation constant
			Value 0
			End
		Channel rotation/x
			Extrapolation constant
			Value 0.000000000
			End
		Channel rotation/y
			Extrapolation constant
			Value 0.000000000
			End
		Channel rotation/z
			Extrapolation constant
			Value 0.000000000
			End
		Channel roll
			Extrapolation constant
			Value 0.000000000
			End
		Channel fov
			Extrapolation constant
			Value 40.000000000
			End
		Channel near
			Extrapolation constant
			Value 1
			End
		Channel far
			Extrapolation constant
			Value 10000
			End
		Channel distance
			Extrapolation constant
			Value 2137.54
			End
		Channel lens_distortion/x
			Extrapolation constant
			Value 0
			End
		Channel lens_distortion/y
			Extrapolation constant
			Value 0
			End
		Channel lens_distortion/magnitude
			Extrapolation constant
			Value 0
			End
		Channel lens_distortion/adjustment
			Extrapolation constant
			Value 0
			End
		Channel lens_distortion/anamorph
			Extrapolation constant
			Value 1
			End
		ChannelEnd
		}
		CamLensFitRes 0
		CamLensFilter 1
		CamLensMode 0
		CamMotionPathMode no
		CamMotionPath
		{
		Path pos_path
			Dimension 3
			Closed no
			Size 0
			End

		Path poi_path
			Dimension 3
			Closed no
			Size 0
			End

		}
		Origin 0
		CamIndex 1000004
		CamPhysicalParameters
		PhysicalCameraEnabled no
		FStop FStop_1
		Film_Type 35mm_Full_Frame
	}
End
Node Axis
	Name axis1
	Number 3
	MotionPath no
	PosX -48
	PosY 21
	OutputsSize 1
	0
	Specifics
	{
		Channel position/x
			Extrapolation linear
			Value 0
			Size 200
			KeyVersion 1
			Key 0
				Frame 1
				Value -459
				Interpolation linear
				End
			Key 1
				Frame 2
				Value -426.528
				Interpolation linear
				RightSlope 32.4724
				LeftSlope 32.4724
				End
			Key 2
				Frame 3
				Value -394.055
				Interpolation linear
				RightSlope 32.4723
				LeftSlope 32.4723
				End
			Key 3
				Frame 4
				Value -361.583
				Interpolation linear
				RightSlope 32.4723
				LeftSlope 32.4723
				End
			Key 4
				Frame 5
				Value -329.111
				Interpolation linear
				RightSlope 32.4724
				LeftSlope 32.4724
				End
			Key 5
				Frame 6
				Value -296.638
				Interpolation linear
				RightSlope 32.4723
				LeftSlope 32.4723
				End
			Key 6
				Frame 7
				Value -264.166
				Interpolation linear
				RightSlope 32.4723
				LeftSlope 32.4723
				End
			Key 7
				Frame 8
				Value -231.694
				Interpolation linear
				RightSlope 32.4724
				LeftSlope 32.4724
				End
			Key 8
				Frame 9
				Value -199.221
				Interpolation linear
				RightSlope 32.4724
				LeftSlope 32.4724
				End
			Key 9
				Frame 10
				Value -166.749
				Interpolation linear
				RightSlope 32.4724
				LeftSlope 32.4724
				End
			Key 10
				Frame 11
				Value -134.277
				Interpolation linear
				RightSlope 32.4723
				LeftSlope 32.4723
				End
			Key 11
				Frame 12
				Value -101.804
				Interpolation linear
				RightSlope 32.4723
				LeftSlope 32.4723
				End
			Key 12
				Frame 13
				Value -69.3319
				Interpolation linear
				RightSlope 32.4724
				LeftSlope 32.4724
				End
			Key 13
				Frame 14
				Value -36.8595
				Interpolation linear
				RightSlope 32.4723
				LeftSlope 32.4723
				End
			Key 14
				Frame 15
				Value -4.38721
				Interpolation linear
				RightSlope 32.4723
				LeftSlope 32.4723
				End
			Key 15
				Frame 16
				Value 28.0851
				Interpolation linear
				RightSlope 32.4724
				LeftSlope 32.4724
				End
			Key 16
				Frame 17
				Value 60.5575
				Interpolation linear
				RightSlope 32.4724
				LeftSlope 32.4724
				End
			Key 17
				Frame 18
				Value 93.0298
				Interpolation linear
				RightSlope 32.4724
				LeftSlope 32.4724
				End
			Key 18
				Frame 19
				Value 125.502
				Interpolation linear
				RightSlope 32.4724
				LeftSlope 32.4724
				End
			Key 19
				Frame 20
				Value 157.975
				Interpolation linear
				RightSlope 32.4724
				LeftSlope 32.4724
				End
			Key 20
				Frame 21
				Value 190.447
				Interpolation linear
				RightSlope 32.4724
				LeftSlope 32.4724
				End
			Key 21
				Frame 22
				Value 222.919
				Interpolation linear
				RightSlope 16.0482
				LeftSlope 16.0482
				End
			Key 22
				Frame 23
				Value 222.543
				Interpolation linear
				RightSlope -0.592209
				LeftSlope -0.592209
				End
			Key 23
				Frame 24
				Value 221.735
				Interpolation linear
				RightSlope -1.01886
				LeftSlope -1.01886
				End
			Key 24
				Frame 25
				Value 220.506
				Interpolation linear
				RightSlope -1.43407
				LeftSlope -1.43407
				End
			Key 25
				Frame 26
				Value 218.867
				Interpolation linear
				RightSlope -1.83785
				LeftSlope -1.83785
				End
			Key 26
				Frame 27
				Value 216.83
				Interpolation linear
				RightSlope -2.23019
				LeftSlope -2.23019
				End
			Key 27
				Frame 28
				Value 214.406
				Interpolation linear
				RightSlope -2.61108
				LeftSlope -2.61108
				End
			Key 28
				Frame 29
				Value 211.608
				Interpolation linear
				RightSlope -2.98053
				LeftSlope -2.98053
				End
			Key 29
				Frame 30
				Value 208.445
				Interpolation linear
				RightSlope -3.33855
				LeftSlope -3.33855
				End
			Key 30
				Frame 31
				Value 204.931
				Interpolation linear
				RightSlope -3.68512
				LeftSlope -3.68512
				End
			Key 31
				Frame 32
				Value 201.075
				Interpolation linear
				RightSlope -4.02025
				LeftSlope -4.02025
				End
			Key 32
				Frame 33
				Value 196.89
				Interpolation linear
				RightSlope -4.34393
				LeftSlope -4.34393
				End
			Key 33
				Frame 34
				Value 192.387
				Interpolation linear
				RightSlope -4.65619
				LeftSlope -4.65619
				End
			Key 34
				Frame 35
				Value 187.578
				Interpolation linear
				RightSlope -4.95701
				LeftSlope -4.95701
				End
			Key 35
				Frame 36
				Value 182.473
				Interpolation linear
				RightSlope -5.24638
				LeftSlope -5.24638
				End
			Key 36
				Frame 37
				Value 177.085
				Interpolation linear
				RightSlope -5.5243
				LeftSlope -5.5243
				End
			Key 37
				Frame 38
				Value 171.425
				Interpolation linear
				RightSlope -5.79079
				LeftSlope -5.79079
				End
			Key 38
				Frame 39
				Value 165.503
				Interpolation linear
				RightSlope -6.04585
				LeftSlope -6.04585
				End
			Key 39
				Frame 40
				Value 159.333
				Interpolation linear
				RightSlope -6.28945
				LeftSlope -6.28945
				End
			Key 40
				Frame 41
				Value 152.924
				Interpolation linear
				RightSlope -6.52161
				LeftSlope -6.52161
				End
			Key 41
				Frame 42
				Value 146.29
				Interpolation linear
				RightSlope -6.74235
				LeftSlope -6.74235
				End
			Key 42
				Frame 43
				Value 139.44
				Interpolation linear
				RightSlope -6.95164
				LeftSlope -6.95164
				End
			Key 43
				Frame 44
				Value 132.386
				Interpolation linear
				RightSlope -7.14948
				LeftSlope -7.14948
				End
			Key 44
				Frame 45
				Value 125.141
				Interpolation linear
				RightSlope -7.33589
				LeftSlope -7.33589
				End
			Key 45
				Frame 46
				Value 117.715
				Interpolation linear
				RightSlope -7.51086
				LeftSlope -7.51086
				End
			Key 46
				Frame 47
				Value 110.119
				Interpolation linear
				RightSlope -7.67439
				LeftSlope -7.67439
				End
			Key 47
				Frame 48
				Value 102.366
				Interpolation linear
				RightSlope -7.82647
				LeftSlope -7.82647
				End
			Key 48
				Frame 49
				Value 94.4661
				Interpolation linear
				RightSlope -7.96711
				LeftSlope -7.96711
				End
			Key 49
				Frame 50
				Value 86.4316
				Interpolation linear
				RightSlope -8.09631
				LeftSlope -8.09631
				End
			Key 50
				Frame 51
				Value 78.2735
				Interpolation linear
				RightSlope -8.21408
				LeftSlope -8.21408
				End
			Key 51
				Frame 52
				Value 70.0034
				Interpolation linear
				RightSlope -8.3204
				LeftSlope -8.3204
				End
			Key 52
				Frame 53
				Value 61.6327
				Interpolation linear
				RightSlope -8.41529
				LeftSlope -8.41529
				End
			Key 53
				Frame 54
				Value 53.1728
				Interpolation linear
				RightSlope -8.49873
				LeftSlope -8.49873
				End
			Key 54
				Frame 55
				Value 44.6353
				Interpolation linear
				RightSlope -8.57074
				LeftSlope -8.57074
				End
			Key 55
				Frame 56
				Value 36.0314
				Interpolation linear
				RightSlope -8.63129
				LeftSlope -8.63129
				End
			Key 56
				Frame 57
				Value 27.3727
				Interpolation linear
				RightSlope -8.68041
				LeftSlope -8.68041
				End
			Key 57
				Frame 58
				Value 18.6705
				Interpolation linear
				RightSlope -8.71811
				LeftSlope -8.71811
				End
			Key 58
				Frame 59
				Value 9.93645
				Interpolation linear
				RightSlope -8.74434
				LeftSlope -8.74434
				End
			Key 59
				Frame 60
				Value 1.18185
				Interpolation linear
				RightSlope -8.75915
				LeftSlope -8.75915
				End
			Key 60
				Frame 61
				Value -7.58185
				Interpolation linear
				RightSlope -8.7625
				LeftSlope -8.7625
				End
			Key 61
				Frame 62
				Value -16.3432
				Interpolation linear
				RightSlope -8.75442
				LeftSlope -8.75442
				End
			Key 62
				Frame 63
				Value -25.0907
				Interpolation linear
				RightSlope -8.7349
				LeftSlope -8.7349
				End
			Key 63
				Frame 64
				Value -33.813
				Interpolation linear
				RightSlope -8.70393
				LeftSlope -8.70393
				End
			Key 64
				Frame 65
				Value -42.4985
				Interpolation linear
				RightSlope -8.66153
				LeftSlope -8.66153
				End
			Key 65
				Frame 66
				Value -51.136
				Interpolation linear
				RightSlope -8.60771
				LeftSlope -8.60771
				End
			Key 66
				Frame 67
				Value -59.714
				Interpolation linear
				RightSlope -8.54242
				LeftSlope -8.54242
				End
			Key 67
				Frame 68
				Value -68.2209
				Interpolation linear
				RightSlope -8.4657
				LeftSlope -8.4657
				End
			Key 68
				Frame 69
				Value -76.6454
				Interpolation linear
				RightSlope -8.37752
				LeftSlope -8.37752
				End
			Key 69
				Frame 70
				Value -84.9759
				Interpolation linear
				RightSlope -8.27791
				LeftSlope -8.27791
				End
			Key 70
				Frame 71
				Value -93.2012
				Interpolation linear
				RightSlope -8.1669
				LeftSlope -8.1669
				End
			Key 71
				Frame 72
				Value -101.31
				Interpolation linear
				RightSlope -8.04439
				LeftSlope -8.04439
				End
			Key 72
				Frame 73
				Value -109.29
				Interpolation linear
				RightSlope -7.91046
				LeftSlope -7.91046
				End
			Key 73
				Frame 74
				Value -117.131
				Interpolation linear
				RightSlope -7.76512
				LeftSlope -7.76512
				End
			Key 74
				Frame 75
				Value -124.82
				Interpolation linear
				RightSlope -7.60831
				LeftSlope -7.60831
				End
			Key 75
				Frame 76
				Value -132.347
				Interpolation linear
				RightSlope -7.44005
				LeftSlope -7.44005
				End
			Key 76
				Frame 77
				Value -139.7
				Interpolation linear
				RightSlope -7.26036
				LeftSlope -7.26036
				End
			Key 77
				Frame 78
				Value -146.868
				Interpolation linear
				RightSlope -7.06924
				LeftSlope -7.06924
				End
			Key 78
				Frame 79
				Value -153.839
				Interpolation linear
				RightSlope -6.86668
				LeftSlope -6.86668
				End
			Key 79
				Frame 80
				Value -160.601
				Interpolation linear
				RightSlope -6.65268
				LeftSlope -6.65268
				End
			Key 80
				Frame 81
				Value -167.144
				Interpolation linear
				RightSlope -6.42722
				LeftSlope -6.42722
				End
			Key 81
				Frame 82
				Value -173.456
				Interpolation linear
				RightSlope -6.19032
				LeftSlope -6.19032
				End
			Key 82
				Frame 83
				Value -179.525
				Interpolation linear
				RightSlope -5.942
				LeftSlope -5.942
				End
			Key 83
				Frame 84
				Value -185.34
				Interpolation linear
				RightSlope -5.68224
				LeftSlope -5.68224
				End
			Key 84
				Frame 85
				Value -190.889
				Interpolation linear
				RightSlope -5.41103
				LeftSlope -5.41103
				End
			Key 85
				Frame 86
				Value -196.162
				Interpolation linear
				RightSlope -5.12836
				LeftSlope -5.12836
				End
			Key 86
				Frame 87
				Value -201.146
				Interpolation linear
				RightSlope -4.83426
				LeftSlope -4.83426
				End
			Key 87
				Frame 88
				Value -205.83
				Interpolation linear
				RightSlope -4.52878
				LeftSlope -4.52878
				End
			Key 88
				Frame 89
				Value -210.204
				Interpolation linear
				RightSlope -4.21181
				LeftSlope -4.21181
				End
			Key 89
				Frame 90
				Value -214.254
				Interpolation linear
				RightSlope -3.88336
				LeftSlope -3.88336
				End
			Key 90
				Frame 91
				Value -217.97
				Interpolation linear
				RightSlope -3.5435
				LeftSlope -3.5435
				End
			Key 91
				Frame 92
				Value -221.341
				Interpolation linear
				RightSlope -3.19225
				LeftSlope -3.19225
				End
			Key 92
				Frame 93
				Value -224.355
				Interpolation linear
				RightSlope -2.82953
				LeftSlope -2.82953
				End
			Key 93
				Frame 94
				Value -227
				Interpolation linear
				RightSlope -1.32263
				LeftSlope -1.32263
				End
			Key 94
				Frame 95
				Value -227
				Interpolation linear
				End
			Key 95
				Frame 96
				Value -227
				Interpolation linear
				End
			Key 96
				Frame 97
				Value -227
				Interpolation linear
				End
			Key 97
				Frame 98
				Value -227
				Interpolation linear
				End
			Key 98
				Frame 99
				Value -227
				Interpolation linear
				End
			Key 99
				Frame 100
				Value -227
				Interpolation linear
				End
			Key 100
				Frame 101
				Value -227
				Interpolation linear
				End
			Key 101
				Frame 102
				Value -227
				Interpolation linear
				End
			Key 102
				Frame 103
				Value -227
				Interpolation linear
				End
			Key 103
				Frame 104
				Value -227
				Interpolation linear
				End
			Key 104
				Frame 105
				Value -227
				Interpolation linear
				End
			Key 105
				Frame 106
				Value -227
				Interpolation linear
				End
			Key 106
				Frame 107
				Value -227
				Interpolation linear
				End
			Key 107
				Frame 108
				Value -227
				Interpolation linear
				End
			Key 108
				Frame 109
				Value -227
				Interpolation linear
				End
			Key 109
				Frame 110
				Value -227
				Interpolation linear
				End
			Key 110
				Frame 111
				Value -227
				Interpolation linear
				End
			Key 111
				Frame 112
				Value -227
				Interpolation linear
				End
			Key 112
				Frame 113
				Value -227
				Interpolation linear
				End
			Key 113
				Frame 114
				Value -227
				Interpolation linear
				End
			Key 114
				Frame 115
				Value -227
				Interpolation linear
				End
			Key 115
				Frame 116
				Value -227
				Interpolation linear
				RightSlope 114.12
				LeftSlope 114.12
				End
			Key 116
				Frame 117
				Value 1.23907
				Interpolation linear
				RightSlope 121.097
				LeftSlope 121.097
				End
			Key 117
				Frame 118
				Value 15.1943
				Interpolation linear
				RightSlope 13.8226
				LeftSlope 13.8226
				End
			Key 118
				Frame 119
				Value 28.8842
				Interpolation linear
				RightSlope 13.5513
				LeftSlope 13.5513
				End
			Key 119
				Frame 120
				Value 42.297
				Interpolation linear
				RightSlope 13.2684
				LeftSlope 13.2684
				End
			Key 120
				Frame 121
				Value 55.421
				Interpolation linear
				RightSlope 12.9738
				LeftSlope 12.9738
				End
			Key 121
				Frame 122
				Value 68.2446
				Interpolation linear
				RightSlope 12.6675
				LeftSlope 12.6675
				End
			Key 122
				Frame 123
				Value 80.7561
				Interpolation linear
				RightSlope 12.3496
				LeftSlope 12.3496
				End
			Key 123
				Frame 124
				Value 92.9438
				Interpolation linear
				RightSlope 12.0199
				LeftSlope 12.0199
				End
			Key 124
				Frame 125
				Value 104.796
				Interpolation linear
				RightSlope 11.6786
				LeftSlope 11.6786
				End
			Key 125
				Frame 126
				Value 116.301
				Interpolation linear
				RightSlope 11.3256
				LeftSlope 11.3256
				End
			Key 126
				Frame 127
				Value 127.447
				Interpolation linear
				RightSlope 10.961
				LeftSlope 10.961
				End
			Key 127
				Frame 128
				Value 138.223
				Interpolation linear
				RightSlope 10.5846
				LeftSlope 10.5846
				End
			Key 128
				Frame 129
				Value 148.616
				Interpolation linear
				RightSlope 10.1966
				LeftSlope 10.1966
				End
			Key 129
				Frame 130
				Value 158.616
				Interpolation linear
				RightSlope 9.79686
				LeftSlope 9.79686
				End
			Key 130
				Frame 131
				Value 168.21
				Interpolation linear
				RightSlope 9.38548
				LeftSlope 9.38548
				End
			Key 131
				Frame 132
				Value 177.387
				Interpolation linear
				RightSlope 8.9624
				LeftSlope 8.9624
				End
			Key 132
				Frame 133
				Value 186.135
				Interpolation linear
				RightSlope 8.52764
				LeftSlope 8.52764
				End
			Key 133
				Frame 134
				Value 194.442
				Interpolation linear
				RightSlope 8.08121
				LeftSlope 8.08121
				End
			Key 134
				Frame 135
				Value 202.297
				Interpolation linear
				RightSlope 7.62309
				LeftSlope 7.62309
				End
			Key 135
				Frame 136
				Value 209.689
				Interpolation linear
				RightSlope 7.15331
				LeftSlope 7.15331
				End
			Key 136
				Frame 137
				Value 216.604
				Interpolation linear
				RightSlope 6.67184
				LeftSlope 6.67184
				End
			Key 137
				Frame 138
				Value 223.032
				Interpolation linear
				RightSlope 6.17867
				LeftSlope 6.17867
				End
			Key 138
				Frame 139
				Value 228.961
				Interpolation linear
				RightSlope 5.67386
				LeftSlope 5.67386
				End
			Key 139
				Frame 140
				Value 234.38
				Interpolation linear
				RightSlope 5.15734
				LeftSlope 5.15734
				End
			Key 140
				Frame 141
				Value 239.276
				Interpolation linear
				RightSlope 4.62914
				LeftSlope 4.62914
				End
			Key 141
				Frame 142
				Value 243.638
				Interpolation linear
				RightSlope 4.08928
				LeftSlope 4.08928
				End
			Key 142
				Frame 143
				Value 247.455
				Interpolation linear
				RightSlope 3.53772
				LeftSlope 3.53772
				End
			Key 143
				Frame 144
				Value 250.714
				Interpolation linear
				RightSlope 2.97449
				LeftSlope 2.97449
				End
			Key 144
				Frame 145
				Value 253.404
				Interpolation linear
				RightSlope 2.39957
				LeftSlope 2.39957
				End
			Key 145
				Frame 146
				Value 255.513
				Interpolation linear
				RightSlope 1.81297
				LeftSlope 1.81297
				End
			Key 146
				Frame 147
				Value 257.03
				Interpolation linear
				RightSlope 1.2147
				LeftSlope 1.2147
				End
			Key 147
				Frame 148
				Value 257.942
				Interpolation linear
				RightSlope 0.604752
				LeftSlope 0.604752
				End
			Key 148
				Frame 149
				Value 258.239
				Interpolation linear
				RightSlope -0.00280762
				LeftSlope -0.00280762
				End
			Key 149
				Frame 150
				Value 257.937
				Interpolation linear
				RightSlope -0.582535
				LeftSlope -0.582535
				End
			Key 150
				Frame 151
				Value 257.074
				Interpolation linear
				RightSlope -1.13128
				LeftSlope -1.13128
				End
			Key 151
				Frame 152
				Value 255.674
				Interpolation linear
				RightSlope -1.65739
				LeftSlope -1.65739
				End
			Key 152
				Frame 153
				Value 253.759
				Interpolation linear
				RightSlope -2.16087
				LeftSlope -2.16087
				End
			Key 153
				Frame 154
				Value 251.352
				Interpolation linear
				RightSlope -2.64172
				LeftSlope -2.64172
				End
			Key 154
				Frame 155
				Value 248.476
				Interpolation linear
				RightSlope -3.09995
				LeftSlope -3.09995
				End
			Key 155
				Frame 156
				Value 245.152
				Interpolation linear
				RightSlope -3.53555
				LeftSlope -3.53555
				End
			Key 156
				Frame 157
				Value 241.405
				Interpolation linear
				RightSlope -3.94851
				LeftSlope -3.94851
				End
			Key 157
				Frame 158
				Value 237.255
				Interpolation linear
				RightSlope -4.33885
				LeftSlope -4.33885
				End
			Key 158
				Frame 159
				Value 232.727
				Interpolation linear
				RightSlope -4.70656
				LeftSlope -4.70656
				End
			Key 159
				Frame 160
				Value 227.842
				Interpolation linear
				RightSlope -5.05164
				LeftSlope -5.05164
				End
			Key 160
				Frame 161
				Value 222.624
				Interpolation linear
				RightSlope -5.37408
				LeftSlope -5.37408
				End
			Key 161
				Frame 162
				Value 217.094
				Interpolation linear
				RightSlope -5.67389
				LeftSlope -5.67389
				End
			Key 162
				Frame 163
				Value 211.276
				Interpolation linear
				RightSlope -5.95109
				LeftSlope -5.95109
				End
			Key 163
				Frame 164
				Value 205.192
				Interpolation linear
				RightSlope -6.20564
				LeftSlope -6.20564
				End
			Key 164
				Frame 165
				Value 198.865
				Interpolation linear
				RightSlope -6.43757
				LeftSlope -6.43757
				End
			Key 165
				Frame 166
				Value 192.317
				Interpolation linear
				RightSlope -6.64687
				LeftSlope -6.64687
				End
			Key 166
				Frame 167
				Value 185.571
				Interpolation linear
				RightSlope -6.83353
				LeftSlope -6.83353
				End
			Key 167
				Frame 168
				Value 178.65
				Interpolation linear
				RightSlope -6.99758
				LeftSlope -6.99758
				End
			Key 168
				Frame 169
				Value 171.576
				Interpolation linear
				RightSlope -7.13898
				LeftSlope -7.13898
				End
			Key 169
				Frame 170
				Value 164.372
				Interpolation linear
				RightSlope -7.25776
				LeftSlope -7.25776
				End
			Key 170
				Frame 171
				Value 157.06
				Interpolation linear
				RightSlope -7.35391
				LeftSlope -7.35391
				End
			Key 171
				Frame 172
				Value 149.664
				Interpolation linear
				RightSlope -7.42744
				LeftSlope -7.42744
				End
			Key 172
				Frame 173
				Value 142.205
				Interpolation linear
				RightSlope -7.47832
				LeftSlope -7.47832
				End
			Key 173
				Frame 174
				Value 134.707
				Interpolation linear
				RightSlope -7.50659
				LeftSlope -7.50659
				End
			Key 174
				Frame 175
				Value 127.192
				Interpolation linear
				RightSlope -7.51222
				LeftSlope -7.51222
				End
			Key 175
				Frame 176
				Value 119.683
				Interpolation linear
				RightSlope -7.49522
				LeftSlope -7.49522
				End
			Key 176
				Frame 177
				Value 112.202
				Interpolation linear
				RightSlope -7.4556
				LeftSlope -7.4556
				End
			Key 177
				Frame 178
				Value 104.772
				Interpolation linear
				RightSlope -7.39333
				LeftSlope -7.39333
				End
			Key 178
				Frame 179
				Value 97.4151
				Interpolation linear
				RightSlope -7.30844
				LeftSlope -7.30844
				End
			Key 179
				Frame 180
				Value 90.1547
				Interpolation linear
				RightSlope -7.20094
				LeftSlope -7.20094
				End
			Key 180
				Frame 181
				Value 83.0132
				Interpolation linear
				RightSlope -7.07079
				LeftSlope -7.07079
				End
			Key 181
				Frame 182
				Value 76.0132
				Interpolation linear
				RightSlope -6.91801
				LeftSlope -6.91801
				End
			Key 182
				Frame 183
				Value 69.1772
				Interpolation linear
				RightSlope -6.74259
				LeftSlope -6.74259
				End
			Key 183
				Frame 184
				Value 62.528
				Interpolation linear
				RightSlope -6.54456
				LeftSlope -6.54456
				End
			Key 184
				Frame 185
				Value 56.0881
				Interpolation linear
				RightSlope -6.32391
				LeftSlope -6.32391
				End
			Key 185
				Frame 186
				Value 49.8802
				Interpolation linear
				RightSlope -6.0806
				LeftSlope -6.0806
				End
			Key 186
				Frame 187
				Value 43.9269
				Interpolation linear
				RightSlope -5.81468
				LeftSlope -5.81468
				End
			Key 187
				Frame 188
				Value 38.2508
				Interpolation linear
				RightSlope -5.52612
				LeftSlope -5.52612
				End
			Key 188
				Frame 189
				Value 32.8746
				Interpolation linear
				RightSlope -5.21493
				LeftSlope -5.21493
				End
			Key 189
				Frame 190
				Value 27.8209
				Interpolation linear
				RightSlope -4.88112
				LeftSlope -4.88112
				End
			Key 190
				Frame 191
				Value 23.1124
				Interpolation linear
				RightSlope -4.5247
				LeftSlope -4.5247
				End
			Key 191
				Frame 192
				Value 18.7715
				Interpolation linear
				RightSlope -4.14561
				LeftSlope -4.14561
				End
			Key 192
				Frame 193
				Value 14.8212
				Interpolation linear
				RightSlope -3.7439
				LeftSlope -3.7439
				End
			Key 193
				Frame 194
				Value 11.2838
				Interpolation linear
				RightSlope -3.31959
				LeftSlope -3.31959
				End
			Key 194
				Frame 195
				Value 8.18198
				Interpolation linear
				RightSlope -2.87261
				LeftSlope -2.87261
				End
			Key 195
				Frame 196
				Value 5.53853
				Interpolation linear
				RightSlope -2.403
				LeftSlope -2.403
				End
			Key 196
				Frame 197
				Value 3.37598
				Interpolation linear
				RightSlope -1.9108
				LeftSlope -1.9108
				End
			Key 197
				Frame 198
				Value 1.71692
				Interpolation linear
				RightSlope -1.39597
				LeftSlope -1.39597
				End
			Key 198
				Frame 199
				Value 0.584045
				Interpolation linear
				RightSlope -0.858459
				LeftSlope -0.858459
				End
			Key 199
				Frame 200
				Value 0
				Interpolation linear
				RightSlope -0.302127
				RightAutomaticSlope no
				End
			Uncollapsed
			End
		Channel position/y
			Extrapolation linear
			Value 0
			Size 6
			KeyVersion 1
			Key 0
				Frame 1
				Value -459
				Interpolation linear
				End
			Key 1
				Frame 22
				Value 222.919
				Interpolation hermite
				RightSlope -0.156017
				LeftSlope 2.49462
				RightAutomaticSlope no
				End
			Key 2
				Frame 94
				Value -227
				Interpolation constant
				RightSlope -2.45723
				LeftSlope -2.33348
				RightAutomaticSlope no
				End
			Key 3
				Frame 117
				Value 1.23907
				Interpolation natural
				RightSlope 14.0841
				LeftSlope 14.0841
				End
			Key 4
				Frame 149
				Value 258.239
				Interpolation hermite
				RightSlope -0.0149286
				LeftSlope -0.0149286
				End
			Key 5
				Frame 200
				Value 0
				Interpolation hermite
				RightSlope -0.302127
				RightAutomaticSlope no
				End
			Uncollapsed
			End
		Channel position/z
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		Channel speed
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		Channel rotation/x
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		Channel rotation/y
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		Channel rotation/z
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		Channel scaling/x
			Extrapolation constant
			Value 100
			Uncollapsed
			End
		Channel scaling/y
			Extrapolation constant
			Value 100
			Uncollapsed
			End
		Channel scaling/z
			Extrapolation constant
			Value 100
			Uncollapsed
			End
		Channel shearing/x
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		Channel shearing/y
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		Channel shearing/z
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		Channel centre/x
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		Channel centre/y
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		Channel centre/z
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		ChannelEnd
		Path position
			Dimension 3
			Closed no
			Size 0
			End

		MBlur yes
		Global no
		LookatNode -1
		Orientation 2
		RigSelection 0
		AutoScale 0
	}
End
ConcreteEnd

#
# outputs
#
CurrentOutputIdx 0
NumberOfOutputs 1
	Index 0
		Uuid 		"7339deb4-8189-458f-80ba-655bb67e6558"
		Name 		"complete_scene"
		Active yes
		CompleteScene yes
		AntiAliasing yes
		MotionBlur yes
		DOF yes
		Camera 1000000
		OutputType 0
		Transparency yes
		UseEmissive yes
		MatteBackColor 1
		MediaMatteIdx 1
		OutputMode 0
		BackgroundMode 0
		BackgroundColor 0 0 0 1
	End
End

#
# layers
#
ActionLayerFileVersion 1.5
CreationDate Mon Mar 21 18:01:59 2011

LayerCount 0
ProxyMode PROXY_OFF

LayerEnd

#
# multitracks
#
ActionMTFileVersion 1.5
CreationDate Mon Mar 21 18:01:59 2011


MultiTrackEnd

#
# drawing order
#
DrawingOrderFileVersion 1.0
CreationDate Mon Mar 21 18:01:59 2011

LookupTableFrame 1
	LookupTableGroup 0
		LookupTableNPath 1
			OutputsSize 1
				OutputIndex 0
				ObjectColor 0
				End
			End
	LookupTableGroup 1
		LookupTableNPath 2
			OutputsSize 0
			End
	LookupTableGroup 2
		LookupTableNPath 0
			OutputsSize 0
			End
	LookupTableGroup 3
		LookupTableNPath 3
			OutputsSize 1
				OutputIndex 0
				ObjectColor 0
				End
			End
DrawingOrderEnd
