Module Action
Program Flame
Version 2012
FileVersion 2
CreationDate Fri May 13 11:35:19 2011

FrameWidth 2048
FrameHeight 1556
FramePixelFormat 131
FrameAspectRatio 2.630000114
FrameDominance 2

	MinFrame 1
	CurrentFrame 1
	MaxFrames 330
	ShadingMode no
	WireframeMode no
	ZBufferMode yes
	FilteringDefault Linear
	FilteringQuality Interactive
	PostProcessMode Interactive
	LinetestMode no
	MultiSample 0
	CurrentCamera 4
	GridMode 3
	Grid3DColour 0.300000012 0.300000012 0.300000012
	CameraPlaneType 0
	PlayLockMode no
	BackupMode yes
	BackupTime 30
	QuickResolution 6
	AntiAliasingLevel 0
	AntiAliasingSoftness 1
	MotionBlurEditor
		Channel 
			Extrapolation constant
			Value 1
			Size 3
			KeyVersion 2
			Key 0
				Frame 50
				Value 1
				RHandleX 50.25
				RHandleY 1
				LHandleX 49.75
				LHandleY 1
				FrameLock yes
				DeleteLock yes
				CurveMode hermite
				CurveOrder cubic
				TangentMode smooth
				End
			Key 1
				Frame 100
				Value 1
				RHandleX 100.25
				RHandleY 1
				LHandleX 99.75
				LHandleY 1
				CurveMode hermite
				CurveOrder cubic
				TangentMode smooth
				End
			Key 2
				Frame 150
				Value 1
				RHandleX 150.25
				RHandleY 1
				LHandleX 149.75
				LHandleY 1
				FrameLock yes
				DeleteLock yes
				CurveMode hermite
				CurveOrder cubic
				TangentMode smooth
				End
			End
		ChannelEnd
	TopLevelChannel
		Channel scene
			Uncollapsed
			End
	ResultCamChannel
		Channel ResultCamera
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		ChannelEnd
MotionBlurTopChannel
		Channel motion_blur
			Uncollapsed
			End
		MotionBlurPhaseChannel
		Channel phase
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		ChannelEnd
	MotionBlurEnableChannel
		Channel enable
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		ChannelEnd
	MotionBlurShutterChannel
		Channel shutter
			Extrapolation constant
			Value 1
			Uncollapsed
			End
		ChannelEnd
	MotionBlurSamplesChannel
		Channel samples
			Extrapolation constant
			Value 5
			Uncollapsed
			End
		ChannelEnd
		DofMode no
		DofSoftness 1
		FogMode Off
		FogColour 0 0 0
		FogStart 0
		FogEnd 1
		FogRange 1
		ProjectorMotionPathMode no
		CamMotionPathMode no
		AxisMotionPathMode no
		LightMotionPathMode no
		PropScalingMode no
		SPropScalingMode yes
		YSnapMode no
		YGridSize 1
		AutoKeyMode yes
		UpdateMode yes
		InteractiveMode 0
		AutoParentMode yes
		ForceProxyUpdate yes
		UndoLevels 10
		DrawIconsMode IconsOn
		IconTransparency 0
		SchematicTransparency 0
		ClipInfo 0
		SubMenu AXIS_MENU
		ColourClamping no
		End

#
# node database
#
ConcreteFileVersion 1.5
CreationDate Fri May 13 11:35:19 2011


WorldScale 1

Node Group
	Name scene
	Number 0
	Child 2
	Child 3
	Child 4
	MotionPath no
	ShadowCaster yes
	ShadowReceiver yes
	ShadowOnly no
	PosX 0
	PosY 0
	Flags SCHEMATIC_HIDDEN
	IsLocked no
	OutputsSize 1
	0
	Specifics
	{
	}
End
Node Camera
	Name DefaultCam
	Number 2
	MotionPath no
	ShadowCaster yes
	ShadowReceiver yes
	ShadowOnly no
	PosX -530
	PosY 258
	IsLocked no
	OutputsSize 0
	Specifics
	{
		CamChannel
		{
		Channel position/x
			Extrapolation constant
			Value 0.000000000
			End
		Channel position/y
			Extrapolation constant
			Value 0.000000000
			End
		Channel position/z
			Extrapolation constant
			Value 2137.537109375
			End
		Channel speed
			Extrapolation constant
			Value 0
			End
		Channel interest/x
			Extrapolation constant
			Value 0.000000000
			End
		Channel interest/y
			Extrapolation constant
			Value 0.000000000
			End
		Channel interest/z
			Extrapolation constant
			Value 0.000000000
			End
		Channel int_speed
			Extrapolation constant
			Value 0
			End
		Channel rotation/x
			Extrapolation constant
			Value 0.000000000
			End
		Channel rotation/y
			Extrapolation constant
			Value 0.000000000
			End
		Channel rotation/z
			Extrapolation constant
			Value 0.000000000
			End
		Channel roll
			Extrapolation constant
			Value 0.000000000
			End
		Channel fov
			Extrapolation constant
			Value 40.000000000
			End
		Channel near
			Extrapolation constant
			Value 1
			End
		Channel far
			Extrapolation constant
			Value 10000
			End
		Channel distance
			Extrapolation constant
			Value 2137.54004
			End
		Channel lens_distortion/x
			Extrapolation constant
			Value 0
			End
		Channel lens_distortion/y
			Extrapolation constant
			Value 0
			End
		Channel lens_distortion/magnitude
			Extrapolation constant
			Value 0
			End
		Channel lens_distortion/adjustment
			Extrapolation constant
			Value 0
			End
		Channel lens_distortion/anamorph
			Extrapolation constant
			Value 1
			End
		ChannelEnd
		}
		CamLensFitRes 0
		CamLensFilter 1
		CamLensMode 0
		CamMotionPathMode no
		CamMotionPath
		{
		Path pos_path
			Dimension 3
			Closed no
			Size 0
			End

		Path poi_path
			Dimension 3
			Closed no
			Size 0
			End

		}
		Origin 0
		CamIndex 0
		CamPhysicalParameters
		PhysicalCameraEnabled no
		FStop FStop_1
		Film_Type 35mm_Full_Frame
	}
End
Node Camera
	Name WorkingCam
	Number 3
	MotionPath no
	ShadowCaster yes
	ShadowReceiver yes
	ShadowOnly no
	PosX -394
	PosY 258
	Flags HIDDEN&SCHEMATIC_HIDDEN
	IsLocked no
	OutputsSize 0
	Specifics
	{
		CamChannel
		{
		Channel position/x
			Extrapolation constant
			Value 0.000000000
			End
		Channel position/y
			Extrapolation constant
			Value 0.000000000
			End
		Channel position/z
			Extrapolation constant
			Value 2137.537109375
			End
		Channel speed
			Extrapolation constant
			Value 0
			End
		Channel interest/x
			Extrapolation constant
			Value 0.000000000
			End
		Channel interest/y
			Extrapolation constant
			Value 0.000000000
			End
		Channel interest/z
			Extrapolation constant
			Value 0.000000000
			End
		Channel int_speed
			Extrapolation constant
			Value 0
			End
		Channel rotation/x
			Extrapolation constant
			Value 0.000000000
			End
		Channel rotation/y
			Extrapolation constant
			Value 0.000000000
			End
		Channel rotation/z
			Extrapolation constant
			Value 0.000000000
			End
		Channel roll
			Extrapolation constant
			Value 0.000000000
			End
		Channel fov
			Extrapolation constant
			Value 40.000000000
			End
		Channel near
			Extrapolation constant
			Value 1
			End
		Channel far
			Extrapolation constant
			Value 10000
			End
		Channel distance
			Extrapolation constant
			Value 2137.54004
			End
		Channel lens_distortion/x
			Extrapolation constant
			Value 0
			End
		Channel lens_distortion/y
			Extrapolation constant
			Value 0
			End
		Channel lens_distortion/magnitude
			Extrapolation constant
			Value 0
			End
		Channel lens_distortion/adjustment
			Extrapolation constant
			Value 0
			End
		Channel lens_distortion/anamorph
			Extrapolation constant
			Value 1
			End
		ChannelEnd
		}
		CamLensFitRes 0
		CamLensFilter 1
		CamLensMode 0
		CamMotionPathMode no
		CamMotionPath
		{
		Path pos_path
			Dimension 3
			Closed no
			Size 0
			End

		Path poi_path
			Dimension 3
			Closed no
			Size 0
			End

		}
		Origin 0
		CamIndex 1000004
		CamPhysicalParameters
		PhysicalCameraEnabled no
		FStop FStop_1
		Film_Type 35mm_Full_Frame
	}
End
Node Axis
	Name axis1
	Number 4
	MotionPath no
	ShadowCaster yes
	ShadowReceiver yes
	ShadowOnly no
	PosX -46
	PosY 21
	IsLocked no
	OutputsSize 1
	0
	Specifics
	{
		Channel position/x
			Extrapolation linear
			Value -459
			Size 330
			KeyVersion 2
			Key 0
				Frame 1
				Value -459
				RHandleX 1.33333337
				RHandleY -459
				LHandleX 0.666666627
				LHandleY -459
				CurveMode hermite
				CurveOrder linear
				End
			Key 1
				Frame 2
				Value -426.527679
				RHandleX 2.33333325
				RHandleY -415.703552
				LHandleX 1.66666663
				LHandleY -437.351807
				CurveMode hermite
				CurveOrder linear
				End
			Key 2
				Frame 3
				Value -394.055328
				RHandleX 3.33333325
				RHandleY -383.231201
				LHandleX 2.66666675
				LHandleY -404.879456
				CurveMode hermite
				CurveOrder linear
				End
			Key 3
				Frame 4
				Value -361.583008
				RHandleX 4.33333349
				RHandleY -350.758911
				LHandleX 3.66666675
				LHandleY -372.407104
				CurveMode hermite
				CurveOrder linear
				End
			Key 4
				Frame 5
				Value -329.110657
				RHandleX 5.33333349
				RHandleY -318.28656
				LHandleX 4.66666651
				LHandleY -339.934753
				CurveMode hermite
				CurveOrder linear
				End
			Key 5
				Frame 6
				Value -296.638336
				RHandleX 6.33333349
				RHandleY -285.81424
				LHandleX 5.66666651
				LHandleY -307.462433
				CurveMode hermite
				CurveOrder linear
				End
			Key 6
				Frame 7
				Value -264.166016
				RHandleX 7.33333349
				RHandleY -253.341904
				LHandleX 6.66666651
				LHandleY -274.990112
				CurveMode hermite
				CurveOrder linear
				End
			Key 7
				Frame 8
				Value -231.69368
				RHandleX 8.33333302
				RHandleY -220.869568
				LHandleX 7.66666651
				LHandleY -242.517792
				CurveMode hermite
				CurveOrder linear
				End
			Key 8
				Frame 9
				Value -199.221344
				RHandleX 9.33333302
				RHandleY -188.397232
				LHandleX 8.66666698
				LHandleY -210.045456
				CurveMode hermite
				CurveOrder linear
				End
			Key 9
				Frame 10
				Value -166.749008
				RHandleX 10.333333
				RHandleY -155.924896
				LHandleX 9.66666698
				LHandleY -177.57312
				CurveMode hermite
				CurveOrder linear
				End
			Key 10
				Frame 11
				Value -134.276672
				RHandleX 11.333333
				RHandleY -123.45256
				LHandleX 10.666667
				LHandleY -145.100784
				CurveMode hermite
				CurveOrder linear
				End
			Key 11
				Frame 12
				Value -101.804352
				RHandleX 12.333333
				RHandleY -90.9802399
				LHandleX 11.666667
				LHandleY -112.628464
				CurveMode hermite
				CurveOrder linear
				End
			Key 12
				Frame 13
				Value -69.332016
				RHandleX 13.333333
				RHandleY -58.5079041
				LHandleX 12.666667
				LHandleY -80.1561279
				CurveMode hermite
				CurveOrder linear
				End
			Key 13
				Frame 14
				Value -36.859684
				RHandleX 14.333333
				RHandleY -26.035574
				LHandleX 13.666667
				LHandleY -47.6837959
				CurveMode hermite
				CurveOrder linear
				End
			Key 14
				Frame 15
				Value -4.38735199
				RHandleX 15.333333
				RHandleY 6.43675852
				LHandleX 14.666667
				LHandleY -15.211463
				CurveMode hermite
				CurveOrder linear
				End
			Key 15
				Frame 16
				Value 28.08498
				RHandleX 16.333334
				RHandleY 38.9090919
				LHandleX 15.666667
				LHandleY 17.26087
				CurveMode hermite
				CurveOrder linear
				End
			Key 16
				Frame 17
				Value 60.557312
				RHandleX 17.333334
				RHandleY 71.381424
				LHandleX 16.666666
				LHandleY 49.7332001
				CurveMode hermite
				CurveOrder linear
				End
			Key 17
				Frame 18
				Value 93.0296478
				RHandleX 18.333334
				RHandleY 103.85376
				LHandleX 17.666666
				LHandleY 82.2055359
				CurveMode hermite
				CurveOrder linear
				End
			Key 18
				Frame 19
				Value 125.501976
				RHandleX 19.333334
				RHandleY 136.32608
				LHandleX 18.666666
				LHandleY 114.677864
				CurveMode hermite
				CurveOrder linear
				End
			Key 19
				Frame 20
				Value 157.974304
				RHandleX 20.333334
				RHandleY 168.798416
				LHandleX 19.666666
				LHandleY 147.150192
				CurveMode hermite
				CurveOrder linear
				End
			Key 20
				Frame 21
				Value 190.44664
				RHandleX 21.333334
				RHandleY 201.270752
				LHandleX 20.666666
				LHandleY 179.622528
				CurveMode hermite
				CurveOrder linear
				End
			Key 21
				Frame 22
				Value 222.919006
				RHandleX 22.333334
				RHandleY 228.268402
				LHandleX 21.666666
				LHandleY 217.569611
				CurveMode hermite
				CurveOrder linear
				End
			Key 22
				Frame 23
				Value 222.542999
				RHandleX 23.333334
				RHandleY 222.345596
				LHandleX 22.666666
				LHandleY 222.740402
				CurveMode hermite
				CurveOrder linear
				End
			Key 23
				Frame 24
				Value 221.734619
				RHandleX 24.333334
				RHandleY 221.395004
				LHandleX 23.666666
				LHandleY 222.074234
				CurveMode hermite
				CurveOrder linear
				End
			Key 24
				Frame 25
				Value 220.505295
				RHandleX 25.333334
				RHandleY 220.027267
				LHandleX 24.666666
				LHandleY 220.983322
				CurveMode hermite
				CurveOrder linear
				End
			Key 25
				Frame 26
				Value 218.866486
				RHandleX 26.333334
				RHandleY 218.253876
				LHandleX 25.666666
				LHandleY 219.479095
				CurveMode hermite
				CurveOrder linear
				End
			Key 26
				Frame 27
				Value 216.829605
				RHandleX 27.333334
				RHandleY 216.086212
				LHandleX 26.666666
				LHandleY 217.572998
				CurveMode hermite
				CurveOrder linear
				End
			Key 27
				Frame 28
				Value 214.406128
				RHandleX 28.333334
				RHandleY 213.535767
				LHandleX 27.666666
				LHandleY 215.276489
				CurveMode hermite
				CurveOrder linear
				End
			Key 28
				Frame 29
				Value 211.607468
				RHandleX 29.333334
				RHandleY 210.613953
				LHandleX 28.666666
				LHandleY 212.600983
				CurveMode hermite
				CurveOrder linear
				End
			Key 29
				Frame 30
				Value 208.445084
				RHandleX 30.333334
				RHandleY 207.332245
				LHandleX 29.666666
				LHandleY 209.557922
				CurveMode hermite
				CurveOrder linear
				End
			Key 30
				Frame 31
				Value 204.930389
				RHandleX 31.333334
				RHandleY 203.702026
				LHandleX 30.666666
				LHandleY 206.158752
				CurveMode hermite
				CurveOrder linear
				End
			Key 31
				Frame 32
				Value 201.07486
				RHandleX 32.3333321
				RHandleY 199.734772
				LHandleX 31.666666
				LHandleY 202.414948
				CurveMode hermite
				CurveOrder linear
				End
			Key 32
				Frame 33
				Value 196.889908
				RHandleX 33.3333321
				RHandleY 195.441925
				LHandleX 32.6666679
				LHandleY 198.337891
				CurveMode hermite
				CurveOrder linear
				End
			Key 33
				Frame 34
				Value 192.386978
				RHandleX 34.3333321
				RHandleY 190.834915
				LHandleX 33.6666679
				LHandleY 193.939041
				CurveMode hermite
				CurveOrder linear
				End
			Key 34
				Frame 35
				Value 187.57753
				RHandleX 35.3333321
				RHandleY 185.925201
				LHandleX 34.6666679
				LHandleY 189.229858
				CurveMode hermite
				CurveOrder linear
				End
			Key 35
				Frame 36
				Value 182.472977
				RHandleX 36.3333321
				RHandleY 180.724182
				LHandleX 35.6666679
				LHandleY 184.221771
				CurveMode hermite
				CurveOrder linear
				End
			Key 36
				Frame 37
				Value 177.084793
				RHandleX 37.3333321
				RHandleY 175.243362
				LHandleX 36.6666679
				LHandleY 178.926224
				CurveMode hermite
				CurveOrder linear
				End
			Key 37
				Frame 38
				Value 171.424377
				RHandleX 38.3333321
				RHandleY 169.49411
				LHandleX 37.6666679
				LHandleY 173.354645
				CurveMode hermite
				CurveOrder linear
				End
			Key 38
				Frame 39
				Value 165.503204
				RHandleX 39.3333321
				RHandleY 163.48793
				LHandleX 38.6666679
				LHandleY 167.518478
				CurveMode hermite
				CurveOrder linear
				End
			Key 39
				Frame 40
				Value 159.332703
				RHandleX 40.3333321
				RHandleY 157.236221
				LHandleX 39.6666679
				LHandleY 161.429184
				CurveMode hermite
				CurveOrder linear
				End
			Key 40
				Frame 41
				Value 152.924316
				RHandleX 41.3333321
				RHandleY 150.750443
				LHandleX 40.6666679
				LHandleY 155.09819
				CurveMode hermite
				CurveOrder linear
				End
			Key 41
				Frame 42
				Value 146.289474
				RHandleX 42.3333321
				RHandleY 144.042023
				LHandleX 41.6666679
				LHandleY 148.536926
				CurveMode hermite
				CurveOrder linear
				End
			Key 42
				Frame 43
				Value 139.439621
				RHandleX 43.3333321
				RHandleY 137.122406
				LHandleX 42.6666679
				LHandleY 141.756836
				CurveMode hermite
				CurveOrder linear
				End
			Key 43
				Frame 44
				Value 132.3862
				RHandleX 44.3333321
				RHandleY 130.003036
				LHandleX 43.6666679
				LHandleY 134.769363
				CurveMode hermite
				CurveOrder linear
				End
			Key 44
				Frame 45
				Value 125.140656
				RHandleX 45.3333321
				RHandleY 122.695358
				LHandleX 44.6666679
				LHandleY 127.585953
				CurveMode hermite
				CurveOrder linear
				End
			Key 45
				Frame 46
				Value 117.714424
				RHandleX 46.3333321
				RHandleY 115.210808
				LHandleX 45.6666679
				LHandleY 120.21804
				CurveMode hermite
				CurveOrder linear
				End
			Key 46
				Frame 47
				Value 110.118942
				RHandleX 47.3333321
				RHandleY 107.560814
				LHandleX 46.6666679
				LHandleY 112.677071
				CurveMode hermite
				CurveOrder linear
				End
			Key 47
				Frame 48
				Value 102.365662
				RHandleX 48.3333321
				RHandleY 99.7568359
				LHandleX 47.6666679
				LHandleY 104.974487
				CurveMode hermite
				CurveOrder linear
				End
			Key 48
				Frame 49
				Value 94.466011
				RHandleX 49.3333321
				RHandleY 91.8103027
				LHandleX 48.6666679
				LHandleY 97.1217194
				CurveMode hermite
				CurveOrder linear
				End
			Key 49
				Frame 50
				Value 86.4314346
				RHandleX 50.3333321
				RHandleY 83.7326584
				LHandleX 49.6666679
				LHandleY 89.1302109
				CurveMode hermite
				CurveOrder linear
				End
			Key 50
				Frame 51
				Value 78.2733765
				RHandleX 51.3333321
				RHandleY 75.535347
				LHandleX 50.6666679
				LHandleY 81.0114059
				CurveMode hermite
				CurveOrder linear
				End
			Key 51
				Frame 52
				Value 70.003273
				RHandleX 52.3333321
				RHandleY 67.229805
				LHandleX 51.6666679
				LHandleY 72.776741
				CurveMode hermite
				CurveOrder linear
				End
			Key 52
				Frame 53
				Value 61.6325645
				RHandleX 53.3333321
				RHandleY 58.8274689
				LHandleX 52.6666679
				LHandleY 64.4376602
				CurveMode hermite
				CurveOrder linear
				End
			Key 53
				Frame 54
				Value 53.1726952
				RHandleX 54.3333321
				RHandleY 50.3397827
				LHandleX 53.6666679
				LHandleY 56.0056076
				CurveMode hermite
				CurveOrder linear
				End
			Key 54
				Frame 55
				Value 44.6351013
				RHandleX 55.3333321
				RHandleY 41.7781906
				LHandleX 54.6666679
				LHandleY 47.492012
				CurveMode hermite
				CurveOrder linear
				End
			Key 55
				Frame 56
				Value 36.0312271
				RHandleX 56.3333321
				RHandleY 33.154129
				LHandleX 55.6666679
				LHandleY 38.9083252
				CurveMode hermite
				CurveOrder linear
				End
			Key 56
				Frame 57
				Value 27.3725071
				RHandleX 57.3333321
				RHandleY 24.4790344
				LHandleX 56.6666679
				LHandleY 30.2659798
				CurveMode hermite
				CurveOrder linear
				End
			Key 57
				Frame 58
				Value 18.6703873
				RHandleX 58.3333321
				RHandleY 15.7643538
				LHandleX 57.6666679
				LHandleY 21.5764198
				CurveMode hermite
				CurveOrder linear
				End
			Key 58
				Frame 59
				Value 9.93630695
				RHandleX 59.3333321
				RHandleY 7.02152681
				LHandleX 58.6666679
				LHandleY 12.8510876
				CurveMode hermite
				CurveOrder linear
				End
			Key 59
				Frame 60
				Value 1.18170476
				RHandleX 60.3333321
				RHandleY -1.73800921
				LHandleX 59.6666679
				LHandleY 4.10141897
				CurveMode hermite
				CurveOrder linear
				End
			Key 60
				Frame 61
				Value -7.58197737
				RHandleX 61.3333321
				RHandleY -10.5028114
				LHandleX 60.6666679
				LHandleY -4.6611433
				CurveMode hermite
				CurveOrder linear
				End
			Key 61
				Frame 62
				Value -16.3432999
				RHandleX 62.3333321
				RHandleY -19.2614403
				LHandleX 61.6666679
				LHandleY -13.4251595
				CurveMode hermite
				CurveOrder linear
				End
			Key 62
				Frame 63
				Value -25.0908203
				RHandleX 63.3333321
				RHandleY -28.0024548
				LHandleX 62.6666679
				LHandleY -22.1791859
				CurveMode hermite
				CurveOrder linear
				End
			Key 63
				Frame 64
				Value -33.8131027
				RHandleX 64.3333359
				RHandleY -36.7144165
				LHandleX 63.6666679
				LHandleY -30.9117889
				CurveMode hermite
				CurveOrder linear
				End
			Key 64
				Frame 65
				Value -42.4986992
				RHandleX 65.3333359
				RHandleY -45.3858795
				LHandleX 64.6666641
				LHandleY -39.6115189
				CurveMode hermite
				CurveOrder linear
				End
			Key 65
				Frame 66
				Value -51.1361771
				RHandleX 66.3333359
				RHandleY -54.0054092
				LHandleX 65.6666641
				LHandleY -48.2669449
				CurveMode hermite
				CurveOrder linear
				End
			Key 66
				Frame 67
				Value -59.7140923
				RHandleX 67.3333359
				RHandleY -62.5615654
				LHandleX 66.6666641
				LHandleY -56.8666191
				CurveMode hermite
				CurveOrder linear
				End
			Key 67
				Frame 68
				Value -68.2210083
				RHandleX 68.3333359
				RHandleY -71.0429077
				LHandleX 67.6666641
				LHandleY -65.3991089
				CurveMode hermite
				CurveOrder linear
				End
			Key 68
				Frame 69
				Value -76.6454773
				RHandleX 69.3333359
				RHandleY -79.4379883
				LHandleX 68.6666641
				LHandleY -73.8529663
				CurveMode hermite
				CurveOrder linear
				End
			Key 69
				Frame 70
				Value -84.976059
				RHandleX 70.3333359
				RHandleY -87.7353668
				LHandleX 69.6666641
				LHandleY -82.2167511
				CurveMode hermite
				CurveOrder linear
				End
			Key 70
				Frame 71
				Value -93.2013245
				RHandleX 71.3333359
				RHandleY -95.9236145
				LHandleX 70.6666641
				LHandleY -90.4790344
				CurveMode hermite
				CurveOrder linear
				End
			Key 71
				Frame 72
				Value -101.309822
				RHandleX 72.3333359
				RHandleY -103.991287
				LHandleX 71.6666641
				LHandleY -98.6283569
				CurveMode hermite
				CurveOrder linear
				End
			Key 72
				Frame 73
				Value -109.290115
				RHandleX 73.3333359
				RHandleY -111.926941
				LHandleX 72.6666641
				LHandleY -106.65329
				CurveMode hermite
				CurveOrder linear
				End
			Key 73
				Frame 74
				Value -117.13076
				RHandleX 74.3333359
				RHandleY -119.719131
				LHandleX 73.6666641
				LHandleY -114.542389
				CurveMode hermite
				CurveOrder linear
				End
			Key 74
				Frame 75
				Value -124.820328
				RHandleX 75.3333359
				RHandleY -127.35643
				LHandleX 74.6666641
				LHandleY -122.284225
				CurveMode hermite
				CurveOrder linear
				End
			Key 75
				Frame 76
				Value -132.347366
				RHandleX 76.3333359
				RHandleY -134.827377
				LHandleX 75.6666641
				LHandleY -129.867355
				CurveMode hermite
				CurveOrder linear
				End
			Key 76
				Frame 77
				Value -139.700424
				RHandleX 77.3333359
				RHandleY -142.120544
				LHandleX 76.6666641
				LHandleY -137.280304
				CurveMode hermite
				CurveOrder linear
				End
			Key 77
				Frame 78
				Value -146.868088
				RHandleX 78.3333359
				RHandleY -149.224503
				LHandleX 77.6666641
				LHandleY -144.511673
				CurveMode hermite
				CurveOrder linear
				End
			Key 78
				Frame 79
				Value -153.838913
				RHandleX 79.3333359
				RHandleY -156.127808
				LHandleX 78.6666641
				LHandleY -151.550018
				CurveMode hermite
				CurveOrder linear
				End
			Key 79
				Frame 80
				Value -160.60144
				RHandleX 80.3333359
				RHandleY -162.819
				LHandleX 79.6666641
				LHandleY -158.383881
				CurveMode hermite
				CurveOrder linear
				End
			Key 80
				Frame 81
				Value -167.144241
				RHandleX 81.3333359
				RHandleY -169.286652
				LHandleX 80.6666641
				LHandleY -165.001831
				CurveMode hermite
				CurveOrder linear
				End
			Key 81
				Frame 82
				Value -173.455872
				RHandleX 82.3333359
				RHandleY -175.519318
				LHandleX 81.6666641
				LHandleY -171.392426
				CurveMode hermite
				CurveOrder linear
				End
			Key 82
				Frame 83
				Value -179.524887
				RHandleX 83.3333359
				RHandleY -181.505554
				LHandleX 82.6666641
				LHandleY -177.54422
				CurveMode hermite
				CurveOrder linear
				End
			Key 83
				Frame 84
				Value -185.339859
				RHandleX 84.3333359
				RHandleY -187.233932
				LHandleX 83.6666641
				LHandleY -183.445786
				CurveMode hermite
				CurveOrder linear
				End
			Key 84
				Frame 85
				Value -190.889343
				RHandleX 85.3333359
				RHandleY -192.693008
				LHandleX 84.6666641
				LHandleY -189.085678
				CurveMode hermite
				CurveOrder linear
				End
			Key 85
				Frame 86
				Value -196.161896
				RHandleX 86.3333359
				RHandleY -197.871353
				LHandleX 85.6666641
				LHandleY -194.452438
				CurveMode hermite
				CurveOrder linear
				End
			Key 86
				Frame 87
				Value -201.146072
				RHandleX 87.3333359
				RHandleY -202.757492
				LHandleX 86.6666641
				LHandleY -199.534653
				CurveMode hermite
				CurveOrder linear
				End
			Key 87
				Frame 88
				Value -205.830444
				RHandleX 88.3333359
				RHandleY -207.340027
				LHandleX 87.6666641
				LHandleY -204.320862
				CurveMode hermite
				CurveOrder linear
				End
			Key 88
				Frame 89
				Value -210.203568
				RHandleX 89.3333359
				RHandleY -211.607498
				LHandleX 88.6666641
				LHandleY -208.799637
				CurveMode hermite
				CurveOrder linear
				End
			Key 89
				Frame 90
				Value -214.253998
				RHandleX 90.3333359
				RHandleY -215.548447
				LHandleX 89.6666641
				LHandleY -212.959549
				CurveMode hermite
				CurveOrder linear
				End
			Key 90
				Frame 91
				Value -217.970291
				RHandleX 91.3333359
				RHandleY -219.151459
				LHandleX 90.6666641
				LHandleY -216.789124
				CurveMode hermite
				CurveOrder linear
				End
			Key 91
				Frame 92
				Value -221.341003
				RHandleX 92.3333359
				RHandleY -222.405075
				LHandleX 91.6666641
				LHandleY -220.276932
				CurveMode hermite
				CurveOrder linear
				End
			Key 92
				Frame 93
				Value -224.354721
				RHandleX 93.3333359
				RHandleY -225.297882
				LHandleX 92.6666641
				LHandleY -223.41156
				CurveMode hermite
				CurveOrder linear
				End
			Key 93
				Frame 94
				Value -227
				RHandleX 94.3333359
				RHandleY -227.440887
				LHandleX 93.6666641
				LHandleY -226.559113
				CurveMode hermite
				CurveOrder linear
				End
			Key 94
				Frame 95
				Value -227
				RHandleX 95.3333359
				RHandleY -227
				LHandleX 94.6666641
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 95
				Frame 96
				Value -227
				RHandleX 96.3333359
				RHandleY -227
				LHandleX 95.6666641
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 96
				Frame 97
				Value -227
				RHandleX 97.3333359
				RHandleY -227
				LHandleX 96.6666641
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 97
				Frame 98
				Value -227
				RHandleX 98.3333359
				RHandleY -227
				LHandleX 97.6666641
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 98
				Frame 99
				Value -227
				RHandleX 99.3333359
				RHandleY -227
				LHandleX 98.6666641
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 99
				Frame 100
				Value -227
				RHandleX 100.333336
				RHandleY -227
				LHandleX 99.6666641
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 100
				Frame 101
				Value -227
				RHandleX 101.333336
				RHandleY -227
				LHandleX 100.666664
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 101
				Frame 102
				Value -227
				RHandleX 102.333336
				RHandleY -227
				LHandleX 101.666664
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 102
				Frame 103
				Value -227
				RHandleX 103.333336
				RHandleY -227
				LHandleX 102.666664
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 103
				Frame 104
				Value -227
				RHandleX 104.333336
				RHandleY -227
				LHandleX 103.666664
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 104
				Frame 105
				Value -227
				RHandleX 105.333336
				RHandleY -227
				LHandleX 104.666664
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 105
				Frame 106
				Value -227
				RHandleX 106.333336
				RHandleY -227
				LHandleX 105.666664
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 106
				Frame 107
				Value -227
				RHandleX 107.333336
				RHandleY -227
				LHandleX 106.666664
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 107
				Frame 108
				Value -227
				RHandleX 108.333336
				RHandleY -227
				LHandleX 107.666664
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 108
				Frame 109
				Value -227
				RHandleX 109.333336
				RHandleY -227
				LHandleX 108.666664
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 109
				Frame 110
				Value -227
				RHandleX 110.333336
				RHandleY -227
				LHandleX 109.666664
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 110
				Frame 111
				Value -227
				RHandleX 111.333336
				RHandleY -227
				LHandleX 110.666664
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 111
				Frame 112
				Value -227
				RHandleX 112.333336
				RHandleY -227
				LHandleX 111.666664
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 112
				Frame 113
				Value -227
				RHandleX 113.333336
				RHandleY -227
				LHandleX 112.666664
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 113
				Frame 114
				Value -227
				RHandleX 114.333336
				RHandleY -227
				LHandleX 113.666664
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 114
				Frame 115
				Value -227
				RHandleX 115.333336
				RHandleY -227
				LHandleX 114.666664
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 115
				Frame 116
				Value -227
				RHandleX 116.333336
				RHandleY -188.960159
				LHandleX 115.666664
				LHandleY -265.039856
				CurveMode hermite
				CurveOrder linear
				End
			Key 116
				Frame 117
				Value 1.23907006
				RHandleX 117.333336
				RHandleY 41.2694969
				LHandleX 116.666664
				LHandleY -38.7913551
				CurveMode hermite
				CurveOrder linear
				End
			Key 117
				Frame 118
				Value 13.182559
				RHandleX 118.333336
				RHandleY 17.1037827
				LHandleX 117.666664
				LHandleY 9.26133633
				CurveMode hermite
				CurveOrder linear
				End
			Key 118
				Frame 119
				Value 24.7664089
				RHandleX 119.333336
				RHandleY 28.592329
				LHandleX 118.666664
				LHandleY 20.9404888
				CurveMode hermite
				CurveOrder linear
				End
			Key 119
				Frame 120
				Value 36.1380844
				RHandleX 120.333336
				RHandleY 39.89114
				LHandleX 119.666664
				LHandleY 32.3850288
				CurveMode hermite
				CurveOrder linear
				End
			Key 120
				Frame 121
				Value 47.2847366
				RHandleX 121.333336
				RHandleY 50.9701729
				LHandleX 120.666664
				LHandleY 43.5993004
				CurveMode hermite
				CurveOrder linear
				End
			Key 121
				Frame 122
				Value 58.2506981
				RHandleX 122.333336
				RHandleY 61.8841858
				LHandleX 121.666664
				LHandleY 54.6172104
				CurveMode hermite
				CurveOrder linear
				End
			Key 122
				Frame 123
				Value 69.0856552
				RHandleX 123.333336
				RHandleY 72.6612549
				LHandleX 122.666664
				LHandleY 65.5100555
				CurveMode hermite
				CurveOrder linear
				End
			Key 123
				Frame 124
				Value 79.7042923
				RHandleX 124.333336
				RHandleY 83.2165909
				LHandleX 123.666664
				LHandleY 76.1919937
				CurveMode hermite
				CurveOrder linear
				End
			Key 124
				Frame 125
				Value 90.159462
				RHandleX 125.333336
				RHandleY 93.6202087
				LHandleX 124.666664
				LHandleY 86.6987152
				CurveMode hermite
				CurveOrder linear
				End
			Key 125
				Frame 126
				Value 100.468781
				RHandleX 126.333336
				RHandleY 103.865822
				LHandleX 125.666664
				LHandleY 97.0717392
				CurveMode hermite
				CurveOrder linear
				End
			Key 126
				Frame 127
				Value 110.541718
				RHandleX 127.333336
				RHandleY 113.878578
				LHandleX 126.666664
				LHandleY 107.204857
				CurveMode hermite
				CurveOrder linear
				End
			Key 127
				Frame 128
				Value 120.489967
				RHandleX 128.333328
				RHandleY 123.767593
				LHandleX 127.666664
				LHandleY 117.212341
				CurveMode hermite
				CurveOrder linear
				End
			Key 128
				Frame 129
				Value 130.207474
				RHandleX 129.333328
				RHandleY 133.415146
				LHandleX 128.666672
				LHandleY 126.999802
				CurveMode hermite
				CurveOrder linear
				End
			Key 129
				Frame 130
				Value 139.736008
				RHandleX 130.333328
				RHandleY 142.880875
				LHandleX 129.666672
				LHandleY 136.591141
				CurveMode hermite
				CurveOrder linear
				End
			Key 130
				Frame 131
				Value 149.076645
				RHandleX 131.333328
				RHandleY 152.151947
				LHandleX 130.666672
				LHandleY 146.001343
				CurveMode hermite
				CurveOrder linear
				End
			Key 131
				Frame 132
				Value 158.187836
				RHandleX 132.333328
				RHandleY 161.195374
				LHandleX 131.666672
				LHandleY 155.180298
				CurveMode hermite
				CurveOrder linear
				End
			Key 132
				Frame 133
				Value 167.121826
				RHandleX 133.333328
				RHandleY 170.049011
				LHandleX 132.666672
				LHandleY 164.194641
				CurveMode hermite
				CurveOrder linear
				End
			Key 133
				Frame 134
				Value 175.750931
				RHandleX 134.333328
				RHandleY 178.592651
				LHandleX 133.666672
				LHandleY 172.90921
				CurveMode hermite
				CurveOrder linear
				End
			Key 134
				Frame 135
				Value 184.172134
				RHandleX 135.333328
				RHandleY 186.930954
				LHandleX 134.666672
				LHandleY 181.413315
				CurveMode hermite
				CurveOrder linear
				End
			Key 135
				Frame 136
				Value 192.303848
				RHandleX 136.333328
				RHandleY 194.966919
				LHandleX 135.666672
				LHandleY 189.640778
				CurveMode hermite
				CurveOrder linear
				End
			Key 136
				Frame 137
				Value 200.150543
				RHandleX 137.333328
				RHandleY 202.718353
				LHandleX 136.666672
				LHandleY 197.582733
				CurveMode hermite
				CurveOrder linear
				End
			Key 137
				Frame 138
				Value 207.710693
				RHandleX 138.333328
				RHandleY 210.1754
				LHandleX 137.666672
				LHandleY 205.245987
				CurveMode hermite
				CurveOrder linear
				End
			Key 138
				Frame 139
				Value 214.938797
				RHandleX 139.333328
				RHandleY 217.285019
				LHandleX 138.666672
				LHandleY 212.592575
				CurveMode hermite
				CurveOrder linear
				End
			Key 139
				Frame 140
				Value 221.788025
				RHandleX 140.333328
				RHandleY 224.005157
				LHandleX 139.666672
				LHandleY 219.570892
				CurveMode hermite
				CurveOrder linear
				End
			Key 140
				Frame 141
				Value 228.241623
				RHandleX 141.333328
				RHandleY 230.322067
				LHandleX 140.666672
				LHandleY 226.161179
				CurveMode hermite
				CurveOrder linear
				End
			Key 141
				Frame 142
				Value 234.270676
				RHandleX 142.333328
				RHandleY 236.198074
				LHandleX 141.666672
				LHandleY 232.343277
				CurveMode hermite
				CurveOrder linear
				End
			Key 142
				Frame 143
				Value 239.805969
				RHandleX 143.333328
				RHandleY 241.560211
				LHandleX 142.666672
				LHandleY 238.051727
				CurveMode hermite
				CurveOrder linear
				End
			Key 143
				Frame 144
				Value 244.796158
				RHandleX 144.333328
				RHandleY 246.356995
				LHandleX 143.666672
				LHandleY 243.235321
				CurveMode hermite
				CurveOrder linear
				End
			Key 144
				Frame 145
				Value 249.170959
				RHandleX 145.333328
				RHandleY 250.513672
				LHandleX 144.666672
				LHandleY 247.828247
				CurveMode hermite
				CurveOrder linear
				End
			Key 145
				Frame 146
				Value 252.852417
				RHandleX 146.333328
				RHandleY 253.940247
				LHandleX 145.666672
				LHandleY 251.764587
				CurveMode hermite
				CurveOrder linear
				End
			Key 146
				Frame 147
				Value 255.697922
				RHandleX 147.333328
				RHandleY 256.483673
				LHandleX 146.666672
				LHandleY 254.91217
				CurveMode hermite
				CurveOrder linear
				End
			Key 147
				Frame 148
				Value 257.566925
				RHandleX 148.333328
				RHandleY 257.990448
				LHandleX 147.666672
				LHandleY 257.143402
				CurveMode hermite
				CurveOrder linear
				End
			Key 148
				Frame 149
				Value 258.239014
				RHandleX 149.333328
				RHandleY 258.269135
				LHandleX 148.666672
				LHandleY 258.208893
				CurveMode hermite
				CurveOrder linear
				End
			Key 149
				Frame 150
				Value 257.747711
				RHandleX 150.333328
				RHandleY 257.43689
				LHandleX 149.666672
				LHandleY 258.058533
				CurveMode hermite
				CurveOrder linear
				End
			Key 150
				Frame 151
				Value 256.374176
				RHandleX 151.333328
				RHandleY 255.779037
				LHandleX 150.666672
				LHandleY 256.96933
				CurveMode hermite
				CurveOrder linear
				End
			Key 151
				Frame 152
				Value 254.176849
				RHandleX 152.333328
				RHandleY 253.323837
				LHandleX 151.666672
				LHandleY 255.029861
				CurveMode hermite
				CurveOrder linear
				End
			Key 152
				Frame 153
				Value 251.256149
				RHandleX 153.333328
				RHandleY 250.171463
				LHandleX 152.666672
				LHandleY 252.340836
				CurveMode hermite
				CurveOrder linear
				End
			Key 153
				Frame 154
				Value 247.668716
				RHandleX 154.333328
				RHandleY 246.372589
				LHandleX 153.666672
				LHandleY 248.964844
				CurveMode hermite
				CurveOrder linear
				End
			Key 154
				Frame 155
				Value 243.479385
				RHandleX 155.333328
				RHandleY 241.987152
				LHandleX 154.666672
				LHandleY 244.971619
				CurveMode hermite
				CurveOrder linear
				End
			Key 155
				Frame 156
				Value 238.715286
				RHandleX 156.333328
				RHandleY 237.039337
				LHandleX 155.666672
				LHandleY 240.391235
				CurveMode hermite
				CurveOrder linear
				End
			Key 156
				Frame 157
				Value 233.423676
				RHandleX 157.333328
				RHandleY 231.579498
				LHandleX 156.666672
				LHandleY 235.267853
				CurveMode hermite
				CurveOrder linear
				End
			Key 157
				Frame 158
				Value 227.650269
				RHandleX 158.333328
				RHandleY 225.660324
				LHandleX 157.666672
				LHandleY 229.640213
				CurveMode hermite
				CurveOrder linear
				End
			Key 158
				Frame 159
				Value 221.484009
				RHandleX 159.333328
				RHandleY 219.355835
				LHandleX 158.666672
				LHandleY 223.612183
				CurveMode hermite
				CurveOrder linear
				End
			Key 159
				Frame 160
				Value 214.881226
				RHandleX 160.333328
				RHandleY 212.629745
				LHandleX 159.666672
				LHandleY 217.132706
				CurveMode hermite
				CurveOrder linear
				End
			Key 160
				Frame 161
				Value 207.975098
				RHandleX 161.333328
				RHandleY 205.612793
				LHandleX 160.666672
				LHandleY 210.337402
				CurveMode hermite
				CurveOrder linear
				End
			Key 161
				Frame 162
				Value 200.707367
				RHandleX 162.333328
				RHandleY 198.229721
				LHandleX 161.666672
				LHandleY 203.185013
				CurveMode hermite
				CurveOrder linear
				End
			Key 162
				Frame 163
				Value 193.109238
				RHandleX 163.333328
				RHandleY 190.545654
				LHandleX 162.666672
				LHandleY 195.672821
				CurveMode hermite
				CurveOrder linear
				End
			Key 163
				Frame 164
				Value 185.325867
				RHandleX 164.333328
				RHandleY 182.678131
				LHandleX 163.666672
				LHandleY 187.973602
				CurveMode hermite
				CurveOrder linear
				End
			Key 164
				Frame 165
				Value 177.222824
				RHandleX 165.333328
				RHandleY 174.492828
				LHandleX 164.666672
				LHandleY 179.95282
				CurveMode hermite
				CurveOrder linear
				End
			Key 165
				Frame 166
				Value 168.945923
				RHandleX 166.333328
				RHandleY 166.153458
				LHandleX 165.666672
				LHandleY 171.738388
				CurveMode hermite
				CurveOrder linear
				End
			Key 166
				Frame 167
				Value 160.468079
				RHandleX 167.333328
				RHandleY 157.613617
				LHandleX 166.666672
				LHandleY 163.32254
				CurveMode hermite
				CurveOrder linear
				End
			Key 167
				Frame 168
				Value 151.819153
				RHandleX 168.333328
				RHandleY 148.902023
				LHandleX 167.666672
				LHandleY 154.736282
				CurveMode hermite
				CurveOrder linear
				End
			Key 168
				Frame 169
				Value 142.965347
				RHandleX 169.333328
				RHandleY 140.006027
				LHandleX 168.666672
				LHandleY 145.924667
				CurveMode hermite
				CurveOrder linear
				End
			Key 169
				Frame 170
				Value 134.063202
				RHandleX 170.333328
				RHandleY 131.082275
				LHandleX 169.666672
				LHandleY 137.044128
				CurveMode hermite
				CurveOrder linear
				End
			Key 170
				Frame 171
				Value 125.079826
				RHandleX 171.333328
				RHandleY 122.065956
				LHandleX 170.666672
				LHandleY 128.093704
				CurveMode hermite
				CurveOrder linear
				End
			Key 171
				Frame 172
				Value 115.979973
				RHandleX 172.333328
				RHandleY 112.943092
				LHandleX 171.666672
				LHandleY 119.016853
				CurveMode hermite
				CurveOrder linear
				End
			Key 172
				Frame 173
				Value 106.858543
				RHandleX 173.333328
				RHandleY 103.808723
				LHandleX 172.666672
				LHandleY 109.908363
				CurveMode hermite
				CurveOrder linear
				End
			Key 173
				Frame 174
				Value 97.681076
				RHandleX 174.333328
				RHandleY 94.6286316
				LHandleX 173.666672
				LHandleY 100.733521
				CurveMode hermite
				CurveOrder linear
				End
			Key 174
				Frame 175
				Value 88.5438614
				RHandleX 175.333328
				RHandleY 85.4993668
				LHandleX 174.666672
				LHandleY 91.588356
				CurveMode hermite
				CurveOrder linear
				End
			Key 175
				Frame 176
				Value 79.4141235
				RHandleX 176.333328
				RHandleY 76.3777466
				LHandleX 175.666672
				LHandleY 82.4505005
				CurveMode hermite
				CurveOrder linear
				End
			Key 176
				Frame 177
				Value 70.3255844
				RHandleX 177.333328
				RHandleY 67.3087845
				LHandleX 176.666672
				LHandleY 73.3423843
				CurveMode hermite
				CurveOrder linear
				End
			Key 177
				Frame 178
				Value 61.3133316
				RHandleX 178.333328
				RHandleY 58.3280449
				LHandleX 177.666672
				LHandleY 64.2986221
				CurveMode hermite
				CurveOrder linear
				End
			Key 178
				Frame 179
				Value 52.4138565
				RHandleX 179.333328
				RHandleY 49.472477
				LHandleX 178.666672
				LHandleY 55.3552361
				CurveMode hermite
				CurveOrder linear
				End
			Key 179
				Frame 180
				Value 43.6650581
				RHandleX 180.333328
				RHandleY 40.770916
				LHandleX 179.666672
				LHandleY 46.5592003
				CurveMode hermite
				CurveOrder linear
				End
			Key 180
				Frame 181
				Value 35.0490074
				RHandleX 181.333328
				RHandleY 32.2161598
				LHandleX 180.666672
				LHandleY 37.881855
				CurveMode hermite
				CurveOrder linear
				End
			Key 181
				Frame 182
				Value 26.6679783
				RHandleX 182.333328
				RHandleY 23.9118538
				LHandleX 181.666672
				LHandleY 29.4241028
				CurveMode hermite
				CurveOrder linear
				End
			Key 182
				Frame 183
				Value 18.5122566
				RHandleX 183.333328
				RHandleY 15.8399963
				LHandleX 182.666672
				LHandleY 21.1845169
				CurveMode hermite
				CurveOrder linear
				End
			Key 183
				Frame 184
				Value 10.6344185
				RHandleX 184.333328
				RHandleY 8.05623722
				LHandleX 183.666672
				LHandleY 13.2125998
				CurveMode hermite
				CurveOrder linear
				End
			Key 184
				Frame 185
				Value 3.04316854
				RHandleX 185.333328
				RHandleY 0.579346836
				LHandleX 184.666672
				LHandleY 5.50699043
				CurveMode hermite
				CurveOrder linear
				End
			Key 185
				Frame 186
				Value -4.14851141
				RHandleX 186.333328
				RHandleY -6.46852589
				LHandleX 185.666672
				LHandleY -1.82849681
				CurveMode hermite
				CurveOrder linear
				End
			Key 186
				Frame 187
				Value -10.8769188
				RHandleX 187.333328
				RHandleY -13.0433617
				LHandleX 186.666672
				LHandleY -8.71047592
				CurveMode hermite
				CurveOrder linear
				End
			Key 187
				Frame 188
				Value -17.1471672
				RHandleX 188.333328
				RHandleY -19.1393795
				LHandleX 187.666672
				LHandleY -15.1549559
				CurveMode hermite
				CurveOrder linear
				End
			Key 188
				Frame 189
				Value -22.8301868
				RHandleX 189.333328
				RHandleY -24.6159248
				LHandleX 188.666672
				LHandleY -21.0444489
				CurveMode hermite
				CurveOrder linear
				End
			Key 189
				Frame 190
				Value -27.8615952
				RHandleX 190.333328
				RHandleY -29.4148254
				LHandleX 189.666672
				LHandleY -26.3083649
				CurveMode hermite
				CurveOrder linear
				End
			Key 190
				Frame 191
				Value -32.1495628
				RHandleX 191.333328
				RHandleY -33.4289589
				LHandleX 190.666672
				LHandleY -30.8701687
				CurveMode hermite
				CurveOrder linear
				End
			Key 191
				Frame 192
				Value -35.5379601
				RHandleX 192.333328
				RHandleY -36.4999046
				LHandleX 191.666672
				LHandleY -34.5760155
				CurveMode hermite
				CurveOrder linear
				End
			Key 192
				Frame 193
				Value -37.9212303
				RHandleX 193.333328
				RHandleY -38.5132179
				LHandleX 192.666672
				LHandleY -37.3292427
				CurveMode hermite
				CurveOrder linear
				End
			Key 193
				Frame 194
				Value -39.0898819
				RHandleX 194.333328
				RHandleY -39.2400627
				LHandleX 193.666672
				LHandleY -38.9397011
				CurveMode hermite
				CurveOrder linear
				End
			Key 194
				Frame 195
				Value -38.8223076
				RHandleX 195.333328
				RHandleY -38.4434586
				LHandleX 194.666672
				LHandleY -39.2011566
				CurveMode hermite
				CurveOrder linear
				End
			Key 195
				Frame 196
				Value -36.8167953
				RHandleX 196.333328
				RHandleY -35.7907715
				LHandleX 195.666672
				LHandleY -37.8428192
				CurveMode hermite
				CurveOrder linear
				End
			Key 196
				Frame 197
				Value -32.6661758
				RHandleX 197.333328
				RHandleY -30.829567
				LHandleX 196.666672
				LHandleY -34.5027847
				CurveMode hermite
				CurveOrder linear
				End
			Key 197
				Frame 198
				Value -25.7971439
				RHandleX 198.333328
				RHandleY -22.9086723
				LHandleX 197.666672
				LHandleY -28.6856155
				CurveMode hermite
				CurveOrder linear
				End
			Key 198
				Frame 199
				Value -15.3353472
				RHandleX 199.333328
				RHandleY -11.0358229
				LHandleX 198.666672
				LHandleY -19.6348705
				CurveMode hermite
				CurveOrder linear
				End
			Key 199
				Frame 200
				Value 0
				RHandleX 200.333328
				RHandleY 2.09454918
				LHandleX 199.666672
				LHandleY -2.09454918
				CurveMode hermite
				CurveOrder linear
				End
			Key 200
				Frame 201
				Value -2.76805162
				RHandleX 201.333328
				RHandleY -3.46634459
				LHandleX 200.666672
				LHandleY -2.06975865
				CurveMode hermite
				CurveOrder linear
				End
			Key 201
				Frame 202
				Value -4.18975782
				RHandleX 202.333328
				RHandleY -4.45141268
				LHandleX 201.666672
				LHandleY -3.92810321
				CurveMode hermite
				CurveOrder linear
				End
			Key 202
				Frame 203
				Value -4.33797979
				RHandleX 203.333328
				RHandleY -4.1857152
				LHandleX 202.666672
				LHandleY -4.49024439
				CurveMode hermite
				CurveOrder linear
				End
			Key 203
				Frame 204
				Value -3.2761693
				RHandleX 204.333328
				RHandleY -2.73253918
				LHandleX 203.666672
				LHandleY -3.81979942
				CurveMode hermite
				CurveOrder linear
				End
			Key 204
				Frame 205
				Value -1.0761987
				RHandleX 205.333328
				RHandleY -0.163032338
				LHandleX 204.666672
				LHandleY -1.9893651
				CurveMode hermite
				CurveOrder linear
				End
			Key 205
				Frame 206
				Value 2.20282912
				RHandleX 206.333328
				RHandleY 3.46545362
				LHandleX 205.666672
				LHandleY 0.940204561
				CurveMode hermite
				CurveOrder linear
				End
			Key 206
				Frame 207
				Value 6.49954891
				RHandleX 207.333328
				RHandleY 8.09117699
				LHandleX 206.666672
				LHandleY 4.90792131
				CurveMode hermite
				CurveOrder linear
				End
			Key 207
				Frame 208
				Value 11.7525959
				RHandleX 208.333328
				RHandleY 13.6474543
				LHandleX 207.666672
				LHandleY 9.85773754
				CurveMode hermite
				CurveOrder linear
				End
			Key 208
				Frame 209
				Value 17.8686981
				RHandleX 209.333328
				RHandleY 20.0450344
				LHandleX 208.666672
				LHandleY 15.6923609
				CurveMode hermite
				CurveOrder linear
				End
			Key 209
				Frame 210
				Value 24.8106174
				RHandleX 210.333328
				RHandleY 27.2587109
				LHandleX 209.666672
				LHandleY 22.362524
				CurveMode hermite
				CurveOrder linear
				End
			Key 210
				Frame 211
				Value 32.5572548
				RHandleX 211.333328
				RHandleY 35.2509308
				LHandleX 210.666672
				LHandleY 29.8635788
				CurveMode hermite
				CurveOrder linear
				End
			Key 211
				Frame 212
				Value 40.9726753
				RHandleX 212.333328
				RHandleY 43.8775558
				LHandleX 211.666672
				LHandleY 38.0677948
				CurveMode hermite
				CurveOrder linear
				End
			Key 212
				Frame 213
				Value 49.9865341
				RHandleX 213.333328
				RHandleY 53.0955849
				LHandleX 212.666672
				LHandleY 46.8774834
				CurveMode hermite
				CurveOrder linear
				End
			Key 213
				Frame 214
				Value 59.6269722
				RHandleX 214.333328
				RHandleY 62.9276924
				LHandleX 213.666672
				LHandleY 56.326252
				CurveMode hermite
				CurveOrder linear
				End
			Key 214
				Frame 215
				Value 69.7908554
				RHandleX 215.333328
				RHandleY 73.2471619
				LHandleX 214.666672
				LHandleY 66.334549
				CurveMode hermite
				CurveOrder linear
				End
			Key 215
				Frame 216
				Value 80.36483
				RHandleX 216.333328
				RHandleY 83.9650803
				LHandleX 215.666672
				LHandleY 76.7645798
				CurveMode hermite
				CurveOrder linear
				End
			Key 216
				Frame 217
				Value 91.3923492
				RHandleX 217.333328
				RHandleY 95.1158752
				LHandleX 216.666672
				LHandleY 87.6688232
				CurveMode hermite
				CurveOrder linear
				End
			Key 217
				Frame 218
				Value 102.705978
				RHandleX 218.333328
				RHandleY 106.533325
				LHandleX 217.666672
				LHandleY 98.8786316
				CurveMode hermite
				CurveOrder linear
				End
			Key 218
				Frame 219
				Value 114.356407
				RHandleX 219.333328
				RHandleY 118.267105
				LHandleX 218.666672
				LHandleY 110.445709
				CurveMode hermite
				CurveOrder linear
				End
			Key 219
				Frame 220
				Value 126.170143
				RHandleX 220.333328
				RHandleY 130.134705
				LHandleX 219.666672
				LHandleY 122.205582
				CurveMode hermite
				CurveOrder linear
				End
			Key 220
				Frame 221
				Value 138.143768
				RHandleX 221.333328
				RHandleY 142.151703
				LHandleX 220.666672
				LHandleY 134.135834
				CurveMode hermite
				CurveOrder linear
				End
			Key 221
				Frame 222
				Value 150.217712
				RHandleX 222.333328
				RHandleY 154.249146
				LHandleX 221.666672
				LHandleY 146.186279
				CurveMode hermite
				CurveOrder linear
				End
			Key 222
				Frame 223
				Value 162.332352
				RHandleX 223.333328
				RHandleY 166.367416
				LHandleX 222.666672
				LHandleY 158.297287
				CurveMode hermite
				CurveOrder linear
				End
			Key 223
				Frame 224
				Value 174.428116
				RHandleX 224.333328
				RHandleY 178.44696
				LHandleX 223.666672
				LHandleY 170.409271
				CurveMode hermite
				CurveOrder linear
				End
			Key 224
				Frame 225
				Value 186.445404
				RHandleX 225.333328
				RHandleY 190.428146
				LHandleX 224.666672
				LHandleY 182.462662
				CurveMode hermite
				CurveOrder linear
				End
			Key 225
				Frame 226
				Value 198.3246
				RHandleX 226.333328
				RHandleY 202.251389
				LHandleX 225.666672
				LHandleY 194.397812
				CurveMode hermite
				CurveOrder linear
				End
			Key 226
				Frame 227
				Value 210.006149
				RHandleX 227.333328
				RHandleY 213.857117
				LHandleX 226.666672
				LHandleY 206.155182
				CurveMode hermite
				CurveOrder linear
				End
			Key 227
				Frame 228
				Value 221.43042
				RHandleX 228.333328
				RHandleY 225.185699
				LHandleX 227.666672
				LHandleY 217.67514
				CurveMode hermite
				CurveOrder linear
				End
			Key 228
				Frame 229
				Value 232.537827
				RHandleX 229.333328
				RHandleY 236.177551
				LHandleX 228.666672
				LHandleY 228.898102
				CurveMode hermite
				CurveOrder linear
				End
			Key 229
				Frame 230
				Value 243.268799
				RHandleX 230.333328
				RHandleY 246.773117
				LHandleX 229.666672
				LHandleY 239.764481
				CurveMode hermite
				CurveOrder linear
				End
			Key 230
				Frame 231
				Value 253.563705
				RHandleX 231.333328
				RHandleY 256.91275
				LHandleX 230.666672
				LHandleY 250.214676
				CurveMode hermite
				CurveOrder linear
				End
			Key 231
				Frame 232
				Value 263.362976
				RHandleX 232.333328
				RHandleY 266.536865
				LHandleX 231.666672
				LHandleY 260.189087
				CurveMode hermite
				CurveOrder linear
				End
			Key 232
				Frame 233
				Value 272.606995
				RHandleX 233.333328
				RHandleY 275.592651
				LHandleX 232.666672
				LHandleY 269.621338
				CurveMode hermite
				CurveOrder linear
				End
			Key 233
				Frame 234
				Value 281.276886
				RHandleX 234.333328
				RHandleY 284.047089
				LHandleX 233.666672
				LHandleY 278.506683
				CurveMode hermite
				CurveOrder linear
				End
			Key 234
				Frame 235
				Value 289.22818
				RHandleX 235.333328
				RHandleY 291.756226
				LHandleX 234.666672
				LHandleY 286.700134
				CurveMode hermite
				CurveOrder linear
				End
			Key 235
				Frame 236
				Value 296.44519
				RHandleX 236.333328
				RHandleY 298.72345
				LHandleX 235.666672
				LHandleY 294.166931
				CurveMode hermite
				CurveOrder linear
				End
			Key 236
				Frame 237
				Value 302.897705
				RHandleX 237.333328
				RHandleY 304.900665
				LHandleX 236.666672
				LHandleY 300.894745
				CurveMode hermite
				CurveOrder linear
				End
			Key 237
				Frame 238
				Value 308.462952
				RHandleX 238.333328
				RHandleY 310.16922
				LHandleX 237.666672
				LHandleY 306.756683
				CurveMode hermite
				CurveOrder linear
				End
			Key 238
				Frame 239
				Value 313.135284
				RHandleX 239.333328
				RHandleY 314.527618
				LHandleX 238.666672
				LHandleY 311.74295
				CurveMode hermite
				CurveOrder linear
				End
			Key 239
				Frame 240
				Value 316.816956
				RHandleX 240.333328
				RHandleY 317.807465
				LHandleX 239.666672
				LHandleY 315.826447
				CurveMode hermite
				CurveOrder linear
				End
			Key 240
				Frame 241
				Value 319.078308
				RHandleX 241.333328
				RHandleY 319.542023
				LHandleX 240.666672
				LHandleY 318.614594
				CurveMode hermite
				CurveOrder linear
				End
			Key 241
				Frame 242
				Value 319.599213
				RHandleX 242.333328
				RHandleY 319.507812
				LHandleX 241.666672
				LHandleY 319.690613
				CurveMode hermite
				CurveOrder linear
				End
			Key 242
				Frame 243
				Value 318.529816
				RHandleX 243.333328
				RHandleY 317.932648
				LHandleX 242.666672
				LHandleY 319.126984
				CurveMode hermite
				CurveOrder linear
				End
			Key 243
				Frame 244
				Value 316.016144
				RHandleX 244.333328
				RHandleY 314.961884
				LHandleX 243.666672
				LHandleY 317.070404
				CurveMode hermite
				CurveOrder linear
				End
			Key 244
				Frame 245
				Value 312.204285
				RHandleX 245.333328
				RHandleY 310.741638
				LHandleX 244.666672
				LHandleY 313.666931
				CurveMode hermite
				CurveOrder linear
				End
			Key 245
				Frame 246
				Value 307.240234
				RHandleX 246.333328
				RHandleY 305.417877
				LHandleX 245.666672
				LHandleY 309.062592
				CurveMode hermite
				CurveOrder linear
				End
			Key 246
				Frame 247
				Value 301.270081
				RHandleX 247.333328
				RHandleY 299.136688
				LHandleX 246.666672
				LHandleY 303.403473
				CurveMode hermite
				CurveOrder linear
				End
			Key 247
				Frame 248
				Value 294.43985
				RHandleX 248.333328
				RHandleY 292.044098
				LHandleX 247.666672
				LHandleY 296.835602
				CurveMode hermite
				CurveOrder linear
				End
			Key 248
				Frame 249
				Value 286.895599
				RHandleX 249.333328
				RHandleY 284.286194
				LHandleX 248.666672
				LHandleY 289.505005
				CurveMode hermite
				CurveOrder linear
				End
			Key 249
				Frame 250
				Value 278.783386
				RHandleX 250.333328
				RHandleY 276.00528
				LHandleX 249.666672
				LHandleY 281.561493
				CurveMode hermite
				CurveOrder linear
				End
			Key 250
				Frame 251
				Value 270.226929
				RHandleX 251.333328
				RHandleY 267.332428
				LHandleX 250.666672
				LHandleY 273.121429
				CurveMode hermite
				CurveOrder linear
				End
			Key 251
				Frame 252
				Value 261.416412
				RHandleX 252.333328
				RHandleY 258.458008
				LHandleX 251.666672
				LHandleY 264.374817
				CurveMode hermite
				CurveOrder linear
				End
			Key 252
				Frame 253
				Value 252.476425
				RHandleX 253.333328
				RHandleY 249.499191
				LHandleX 252.666672
				LHandleY 255.453659
				CurveMode hermite
				CurveOrder linear
				End
			Key 253
				Frame 254
				Value 243.553055
				RHandleX 254.333328
				RHandleY 240.605698
				LHandleX 253.666672
				LHandleY 246.500412
				CurveMode hermite
				CurveOrder linear
				End
			Key 254
				Frame 255
				Value 234.792313
				RHandleX 255.333328
				RHandleY 231.923523
				LHandleX 254.666672
				LHandleY 237.661102
				CurveMode hermite
				CurveOrder linear
				End
			Key 255
				Frame 256
				Value 226.340286
				RHandleX 256.333344
				RHandleY 223.59874
				LHandleX 255.666672
				LHandleY 229.081833
				CurveMode hermite
				CurveOrder linear
				End
			Key 256
				Frame 257
				Value 218.343002
				RHandleX 257.333344
				RHandleY 215.777374
				LHandleX 256.666656
				LHandleY 220.90863
				CurveMode hermite
				CurveOrder linear
				End
			Key 257
				Frame 258
				Value 210.946518
				RHandleX 258.333344
				RHandleY 208.605499
				LHandleX 257.666656
				LHandleY 213.287537
				CurveMode hermite
				CurveOrder linear
				End
			Key 258
				Frame 259
				Value 204.29686
				RHandleX 259.333344
				RHandleY 202.229126
				LHandleX 258.666656
				LHandleY 206.364594
				CurveMode hermite
				CurveOrder linear
				End
			Key 259
				Frame 260
				Value 198.540115
				RHandleX 260.333344
				RHandleY 196.793472
				LHandleX 259.666656
				LHandleY 200.286758
				CurveMode hermite
				CurveOrder linear
				End
			Key 260
				Frame 261
				Value 193.816956
				RHandleX 261.333344
				RHandleY 192.066452
				LHandleX 260.666656
				LHandleY 195.567459
				CurveMode hermite
				CurveOrder linear
				End
			Key 261
				Frame 262
				Value 188.037125
				RHandleX 262.333344
				RHandleY 185.502258
				LHandleX 261.666656
				LHandleY 190.571991
				CurveMode hermite
				CurveOrder linear
				End
			Key 262
				Frame 263
				Value 178.607712
				RHandleX 263.333344
				RHandleY 174.723175
				LHandleX 262.666656
				LHandleY 182.492249
				CurveMode hermite
				CurveOrder linear
				End
			Key 263
				Frame 264
				Value 164.729889
				RHandleX 264.333344
				RHandleY 159.172318
				LHandleX 263.666656
				LHandleY 170.28746
				CurveMode hermite
				CurveOrder linear
				End
			Key 264
				Frame 265
				Value 145.262238
				RHandleX 265.333344
				RHandleY 137.568787
				LHandleX 264.666656
				LHandleY 152.955688
				CurveMode hermite
				CurveOrder linear
				End
			Key 265
				Frame 266
				Value 118.569221
				RHandleX 266.333344
				RHandleY 108.067421
				LHandleX 265.666656
				LHandleY 129.07103
				CurveMode hermite
				CurveOrder linear
				End
			Key 266
				Frame 267
				Value 82.2514191
				RHandleX 267.333344
				RHandleY 67.9241409
				LHandleX 266.666656
				LHandleY 96.5786972
				CurveMode hermite
				CurveOrder linear
				End
			Key 267
				Frame 268
				Value 32.6055298
				RHandleX 268.333344
				RHandleY 13.0726089
				LHandleX 267.666656
				LHandleY 52.1384506
				CurveMode hermite
				CurveOrder linear
				End
			Key 268
				Frame 269
				Value -34.9461021
				RHandleX 269.333344
				RHandleY -60.1569443
				LHandleX 268.666656
				LHandleY -9.73526096
				CurveMode hermite
				CurveOrder linear
				End
			Key 269
				Frame 270
				Value -118.659508
				RHandleX 270.333344
				RHandleY -144.114502
				LHandleX 269.666656
				LHandleY -93.2045135
				CurveMode hermite
				CurveOrder linear
				End
			Key 270
				Frame 271
				Value -187.676086
				RHandleX 271.333344
				RHandleY -203.680801
				LHandleX 270.666656
				LHandleY -171.671371
				CurveMode hermite
				CurveOrder linear
				End
			Key 271
				Frame 272
				Value -214.687836
				RHandleX 272.333344
				RHandleY -218.570633
				LHandleX 271.666656
				LHandleY -210.805038
				CurveMode hermite
				CurveOrder linear
				End
			Key 272
				Frame 273
				Value -210.972855
				RHandleX 273.333344
				RHandleY -208.036453
				LHandleX 272.666656
				LHandleY -213.909256
				CurveMode hermite
				CurveOrder linear
				End
			Key 273
				Frame 274
				Value -197.069458
				RHandleX 274.333344
				RHandleY -192.434998
				LHandleX 273.666656
				LHandleY -201.703918
				CurveMode hermite
				CurveOrder linear
				End
			Key 274
				Frame 275
				Value -183.166046
				RHandleX 275.333344
				RHandleY -178.531586
				LHandleX 274.666656
				LHandleY -187.800507
				CurveMode hermite
				CurveOrder linear
				End
			Key 275
				Frame 276
				Value -169.26265
				RHandleX 276.333344
				RHandleY -164.628189
				LHandleX 275.666656
				LHandleY -173.89711
				CurveMode hermite
				CurveOrder linear
				End
			Key 276
				Frame 277
				Value -155.359238
				RHandleX 277.333344
				RHandleY -150.724777
				LHandleX 276.666656
				LHandleY -159.993698
				CurveMode hermite
				CurveOrder linear
				End
			Key 277
				Frame 278
				Value -141.455841
				RHandleX 278.333344
				RHandleY -136.821381
				LHandleX 277.666656
				LHandleY -146.090302
				CurveMode hermite
				CurveOrder linear
				End
			Key 278
				Frame 279
				Value -127.552437
				RHandleX 279.333344
				RHandleY -122.917969
				LHandleX 278.666656
				LHandleY -132.186905
				CurveMode hermite
				CurveOrder linear
				End
			Key 279
				Frame 280
				Value -113.649033
				RHandleX 280.333344
				RHandleY -109.014565
				LHandleX 279.666656
				LHandleY -118.283501
				CurveMode hermite
				CurveOrder linear
				End
			Key 280
				Frame 281
				Value -99.7456284
				RHandleX 281.333344
				RHandleY -95.1111603
				LHandleX 280.666656
				LHandleY -104.380096
				CurveMode hermite
				CurveOrder linear
				End
			Key 281
				Frame 282
				Value -85.8422241
				RHandleX 282.333344
				RHandleY -81.207756
				LHandleX 281.666656
				LHandleY -90.4766922
				CurveMode hermite
				CurveOrder linear
				End
			Key 282
				Frame 283
				Value -71.9388275
				RHandleX 283.333344
				RHandleY -67.3043594
				LHandleX 282.666656
				LHandleY -76.5732956
				CurveMode hermite
				CurveOrder linear
				End
			Key 283
				Frame 284
				Value -58.0354156
				RHandleX 284.333344
				RHandleY -53.4009476
				LHandleX 283.666656
				LHandleY -62.6698837
				CurveMode hermite
				CurveOrder linear
				End
			Key 284
				Frame 285
				Value -44.132019
				RHandleX 285.333344
				RHandleY -39.497551
				LHandleX 284.666656
				LHandleY -48.7664871
				CurveMode hermite
				CurveOrder linear
				End
			Key 285
				Frame 286
				Value -30.2286072
				RHandleX 286.333344
				RHandleY -25.5941391
				LHandleX 285.666656
				LHandleY -34.8630753
				CurveMode hermite
				CurveOrder linear
				End
			Key 286
				Frame 287
				Value -16.3252106
				RHandleX 287.333344
				RHandleY -11.6907425
				LHandleX 286.666656
				LHandleY -20.9596786
				CurveMode hermite
				CurveOrder linear
				End
			Key 287
				Frame 288
				Value -2.42179871
				RHandleX 288.333344
				RHandleY 2.21266937
				LHandleX 287.666656
				LHandleY -7.05626678
				CurveMode hermite
				CurveOrder linear
				End
			Key 288
				Frame 289
				Value 11.4815979
				RHandleX 289.333344
				RHandleY 16.1160641
				LHandleX 288.666656
				LHandleY 6.84713221
				CurveMode hermite
				CurveOrder linear
				End
			Key 289
				Frame 290
				Value 25.3849945
				RHandleX 290.333344
				RHandleY 30.0194626
				LHandleX 289.666656
				LHandleY 20.7505264
				CurveMode hermite
				CurveOrder linear
				End
			Key 290
				Frame 291
				Value 39.2884064
				RHandleX 291.333344
				RHandleY 43.9228783
				LHandleX 290.666656
				LHandleY 34.6539345
				CurveMode hermite
				CurveOrder linear
				End
			Key 291
				Frame 292
				Value 53.1918182
				RHandleX 292.333344
				RHandleY 57.8262825
				LHandleX 291.666656
				LHandleY 48.557354
				CurveMode hermite
				CurveOrder linear
				End
			Key 292
				Frame 293
				Value 67.0951996
				RHandleX 293.333344
				RHandleY 71.7296677
				LHandleX 292.666656
				LHandleY 62.4607353
				CurveMode hermite
				CurveOrder linear
				End
			Key 293
				Frame 294
				Value 80.9986115
				RHandleX 294.333344
				RHandleY 85.6330795
				LHandleX 293.666656
				LHandleY 76.3641434
				CurveMode hermite
				CurveOrder linear
				End
			Key 294
				Frame 295
				Value 94.9020233
				RHandleX 295.333344
				RHandleY 99.5364914
				LHandleX 294.666656
				LHandleY 90.2675552
				CurveMode hermite
				CurveOrder linear
				End
			Key 295
				Frame 296
				Value 108.805435
				RHandleX 296.333344
				RHandleY 113.439903
				LHandleX 295.666656
				LHandleY 104.170967
				CurveMode hermite
				CurveOrder linear
				End
			Key 296
				Frame 297
				Value 122.708817
				RHandleX 297.333344
				RHandleY 127.343285
				LHandleX 296.666656
				LHandleY 118.074348
				CurveMode hermite
				CurveOrder linear
				End
			Key 297
				Frame 298
				Value 136.612228
				RHandleX 298.333344
				RHandleY 141.246704
				LHandleX 297.666656
				LHandleY 131.977753
				CurveMode hermite
				CurveOrder linear
				End
			Key 298
				Frame 299
				Value 150.51564
				RHandleX 299.333344
				RHandleY 155.150101
				LHandleX 298.666656
				LHandleY 145.88118
				CurveMode hermite
				CurveOrder linear
				End
			Key 299
				Frame 300
				Value 164.419022
				RHandleX 300.333344
				RHandleY 169.053482
				LHandleX 299.666656
				LHandleY 159.784561
				CurveMode hermite
				CurveOrder linear
				End
			Key 300
				Frame 301
				Value 178.322433
				RHandleX 301.333344
				RHandleY 182.956909
				LHandleX 300.666656
				LHandleY 173.687958
				CurveMode hermite
				CurveOrder linear
				End
			Key 301
				Frame 302
				Value 192.225845
				RHandleX 302.333344
				RHandleY 196.860321
				LHandleX 301.666656
				LHandleY 187.59137
				CurveMode hermite
				CurveOrder linear
				End
			Key 302
				Frame 303
				Value 206.129257
				RHandleX 303.333344
				RHandleY 210.763718
				LHandleX 302.666656
				LHandleY 201.494797
				CurveMode hermite
				CurveOrder linear
				End
			Key 303
				Frame 304
				Value 220.032639
				RHandleX 304.333344
				RHandleY 224.667099
				LHandleX 303.666656
				LHandleY 215.398178
				CurveMode hermite
				CurveOrder linear
				End
			Key 304
				Frame 305
				Value 233.93605
				RHandleX 305.333344
				RHandleY 238.570526
				LHandleX 304.666656
				LHandleY 229.301575
				CurveMode hermite
				CurveOrder linear
				End
			Key 305
				Frame 306
				Value 247.839462
				RHandleX 306.333344
				RHandleY 252.473923
				LHandleX 305.666656
				LHandleY 243.205002
				CurveMode hermite
				CurveOrder linear
				End
			Key 306
				Frame 307
				Value 261.742859
				RHandleX 307.333344
				RHandleY 266.377319
				LHandleX 306.666656
				LHandleY 257.108398
				CurveMode hermite
				CurveOrder linear
				End
			Key 307
				Frame 308
				Value 275.64624
				RHandleX 308.333344
				RHandleY 280.280701
				LHandleX 307.666656
				LHandleY 271.01178
				CurveMode hermite
				CurveOrder linear
				End
			Key 308
				Frame 309
				Value 289.549683
				RHandleX 309.333344
				RHandleY 294.184143
				LHandleX 308.666656
				LHandleY 284.915222
				CurveMode hermite
				CurveOrder linear
				End
			Key 309
				Frame 310
				Value 303.453064
				RHandleX 310.333344
				RHandleY 308.087524
				LHandleX 309.666656
				LHandleY 298.818604
				CurveMode hermite
				CurveOrder linear
				End
			Key 310
				Frame 311
				Value 317.356506
				RHandleX 311.333344
				RHandleY 321.990967
				LHandleX 310.666656
				LHandleY 312.722046
				CurveMode hermite
				CurveOrder linear
				End
			Key 311
				Frame 312
				Value 331.259888
				RHandleX 312.333344
				RHandleY 335.894348
				LHandleX 311.666656
				LHandleY 326.625427
				CurveMode hermite
				CurveOrder linear
				End
			Key 312
				Frame 313
				Value 345.163269
				RHandleX 313.333344
				RHandleY 349.797729
				LHandleX 312.666656
				LHandleY 340.528809
				CurveMode hermite
				CurveOrder linear
				End
			Key 313
				Frame 314
				Value 359.066711
				RHandleX 314.333344
				RHandleY 363.701172
				LHandleX 313.666656
				LHandleY 354.432251
				CurveMode hermite
				CurveOrder linear
				End
			Key 314
				Frame 315
				Value 372.970093
				RHandleX 315.333344
				RHandleY 377.604553
				LHandleX 314.666656
				LHandleY 368.335632
				CurveMode hermite
				CurveOrder linear
				End
			Key 315
				Frame 316
				Value 386.873474
				RHandleX 316.333344
				RHandleY 391.507935
				LHandleX 315.666656
				LHandleY 382.239014
				CurveMode hermite
				CurveOrder linear
				End
			Key 316
				Frame 317
				Value 400.776917
				RHandleX 317.333344
				RHandleY 405.411377
				LHandleX 316.666656
				LHandleY 396.142456
				CurveMode hermite
				CurveOrder linear
				End
			Key 317
				Frame 318
				Value 414.680298
				RHandleX 318.333344
				RHandleY 419.314758
				LHandleX 317.666656
				LHandleY 410.045837
				CurveMode hermite
				CurveOrder linear
				End
			Key 318
				Frame 319
				Value 428.58374
				RHandleX 319.333344
				RHandleY 433.218201
				LHandleX 318.666656
				LHandleY 423.94928
				CurveMode hermite
				CurveOrder linear
				End
			Key 319
				Frame 320
				Value 442.487122
				RHandleX 320.333344
				RHandleY 447.121582
				LHandleX 319.666656
				LHandleY 437.852661
				CurveMode hermite
				CurveOrder linear
				End
			Key 320
				Frame 321
				Value 456.390503
				RHandleX 321.333344
				RHandleY 461.024963
				LHandleX 320.666656
				LHandleY 451.756042
				CurveMode hermite
				CurveOrder linear
				End
			Key 321
				Frame 322
				Value 470.293945
				RHandleX 322.333344
				RHandleY 474.928406
				LHandleX 321.666656
				LHandleY 465.659485
				CurveMode hermite
				CurveOrder linear
				End
			Key 322
				Frame 323
				Value 484.197327
				RHandleX 323.333344
				RHandleY 488.831787
				LHandleX 322.666656
				LHandleY 479.562866
				CurveMode hermite
				CurveOrder linear
				End
			Key 323
				Frame 324
				Value 498.100708
				RHandleX 324.333344
				RHandleY 502.735168
				LHandleX 323.666656
				LHandleY 493.466248
				CurveMode hermite
				CurveOrder linear
				End
			Key 324
				Frame 325
				Value 512.00415
				RHandleX 325.333344
				RHandleY 516.638611
				LHandleX 324.666656
				LHandleY 507.36969
				CurveMode hermite
				CurveOrder linear
				End
			Key 325
				Frame 326
				Value 525.907532
				RHandleX 326.333344
				RHandleY 530.541992
				LHandleX 325.666656
				LHandleY 521.273071
				CurveMode hermite
				CurveOrder linear
				End
			Key 326
				Frame 327
				Value 539.810913
				RHandleX 327.333344
				RHandleY 544.445374
				LHandleX 326.666656
				LHandleY 535.176453
				CurveMode hermite
				CurveOrder linear
				End
			Key 327
				Frame 328
				Value 553.714355
				RHandleX 328.333344
				RHandleY 558.348816
				LHandleX 327.666656
				LHandleY 549.079895
				CurveMode hermite
				CurveOrder linear
				End
			Key 328
				Frame 329
				Value 567.617737
				RHandleX 329.333344
				RHandleY 572.252197
				LHandleX 328.666656
				LHandleY 562.983276
				CurveMode hermite
				CurveOrder linear
				End
			Key 329
				Frame 330
				Value 581.521118
				RHandleX 330.333344
				RHandleY 581.521118
				LHandleX 329.666656
				LHandleY 581.521118
				CurveMode hermite
				CurveOrder linear
				End
			Uncollapsed
			End
		Channel position/y
			Extrapolation linear
			Value -459
			Size 9
			KeyVersion 2
			Key 0
				Frame 1
				Value -459
				RHandleX 8
				RHandleY -459
				LHandleX -6
				LHandleY -459
				CurveMode hermite
				CurveOrder linear
				End
			Key 1
				Frame 22
				Value 222.919006
				RHandleX 22.25
				RHandleY 222.880005
				LHandleX 21.75
				LHandleY 222.958008
				CurveMode hermite
				CurveOrder cubic
				RightAutomaticSlope no
				LeftAutomaticSlope no
				TangentMode manual
				End
			Key 2
				Frame 94
				Value -227
				RHandleX 94.25
				RHandleY -227.614304
				LHandleX 93.75
				LHandleY -226.385696
				CurveMode hermite
				CurveOrder constant
				End
			Key 3
				Frame 117
				Value 1.23907006
				RHandleX 117.25
				RHandleY 4.76008224
				LHandleX 109.333336
				LHandleY -66.4003067
				CurveMode bezier
				CurveOrder cubic
				RightAutomaticSlope no
				TangentMode manual
				End
			Key 4
				Frame 149
				Value 258.239014
				RHandleX 166
				RHandleY 257.985229
				LHandleX 138.333328
				LHandleY 258.398254
				CurveMode bezier
				CurveOrder cubic
				TangentMode smooth
				End
			Key 5
				Frame 200
				Value 0
				RHandleX 213.17305
				RHandleY -45.5487976
				LHandleX 190.921555
				LHandleY -167.847229
				CurveMode bezier
				CurveOrder cubic
				RightAutomaticSlope no
				LeftAutomaticSlope no
				BreakSlope yes
				TangentMode independent
				End
			Key 6
				Frame 240
				Value 316.816956
				RHandleX 247
				RHandleY 339.058258
				LHandleX 226.666672
				LHandleY 274.452606
				CurveMode bezier
				CurveOrder cubic
				TangentMode smooth
				End
			Key 7
				Frame 261
				Value 193.816956
				RHandleX 270.656097
				RHandleY 153.75235
				LHandleX 254
				LHandleY 222.861008
				CurveMode bezier
				CurveOrder cubic
				RightAutomaticSlope no
				LeftAutomaticSlope no
				TangentMode manual
				End
			Key 8
				Frame 273
				Value -210.972855
				RHandleX 278.382324
				RHandleY -136.140228
				LHandleX 269
				LHandleY -266.586456
				CurveMode bezier
				CurveOrder cubic
				RightAutomaticSlope no
				LeftAutomaticSlope no
				TangentMode manual
				End
			Uncollapsed
			End
		Channel position/z
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		Channel speed
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		Channel rotation/x
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		Channel rotation/y
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		Channel rotation/z
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		Channel scaling/x
			Extrapolation constant
			Value 100
			Uncollapsed
			End
		Channel scaling/y
			Extrapolation constant
			Value 100
			Uncollapsed
			End
		Channel scaling/z
			Extrapolation constant
			Value 100
			Uncollapsed
			End
		Channel shearing/x
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		Channel shearing/y
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		Channel shearing/z
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		Channel centre/x
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		Channel centre/y
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		Channel centre/z
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		ChannelEnd
		Path position
			Dimension 3
			Closed no
			Size 0
			End

		MBlur yes
		Global no
		LookatNode -1
		Orientation 2
		RigSelection 0
		AutoScale 0
	}
End
ConcreteEnd

#
# outputs
#
CurrentOutputIdx 0
NumberOfOutputs 1
	Index 0
		Uuid 		"7339deb4-8189-458f-80ba-655bb67e6558"
		Name 		"complete_scene"
		Active yes
		CompleteScene yes
		AntiAliasing yes
		UseGMask yes
		MotionBlur yes
		DOF yes
		Camera 1000000
		Light -1
		OutputType 0
		Transparency yes
		UseEmissive yes
		UseAmbient yes
		MatteBackColor 1
		MediaMatteIdx 1
		ZDepthThreshold 0
		BilateralFilter 0
		MaxZDepth 100
		OutputMode 0
		GMaskBlendType 0
		BackgroundMode 0
		ShadowMode 2
		GMaskTransparency 0
		GMaskBlending 1
		GMaskBlendModel 0
		GMaskCorrelation 0
		BackgroundColor 0 0 0 1
	End
End

#
# layers
#
ActionLayerFileVersion 1.5
CreationDate Fri May 13 11:35:19 2011

LayerCount 0
ProxyMode PROXY_OFF

LayerEnd

#
# multitracks
#
ActionMTFileVersion 1.5
CreationDate Fri May 13 11:35:19 2011


MultiTrackEnd

#
# drawing order
#
DrawingOrderFileVersion 1.0
CreationDate Fri May 13 11:35:19 2011

LookupTableFrame 1
	LookupTableGroup 0
		LookupTableNPath 1
			OutputsSize 1
				OutputIndex 0
				ObjectColor 0
				End
			End
	LookupTableGroup 1
		LookupTableNPath 2
			OutputsSize 0
			End
	LookupTableGroup 2
		LookupTableNPath 0
			OutputsSize 0
			End
	LookupTableGroup 3
		LookupTableNPath 3
			OutputsSize 1
				OutputIndex 0
				ObjectColor 0
				End
			End
LookupAutoKey no
DrawingOrderEnd
