Module Action
Program Flame
Version 2012
FileVersion 2
CreationDate Mon May 16 10:00:56 2011

FrameWidth 2048
FrameHeight 1556
FramePixelFormat 131
FrameAspectRatio 2.630000114
FrameDominance 2

	MinFrame 1
	CurrentFrame 200
	MaxFrames 200
	ShadingMode no
	WireframeMode no
	ZBufferMode yes
	FilteringDefault Linear
	FilteringQuality Interactive
	PostProcessMode Interactive
	LinetestMode no
	MultiSample 0
	CurrentCamera 4
	GridMode 3
	Grid3DColour 0.300000012 0.300000012 0.300000012
	CameraPlaneType 0
	PlayLockMode no
	BackupMode yes
	BackupTime 30
	QuickResolution 6
	AntiAliasingLevel 0
	AntiAliasingSoftness 1
	MotionBlurEditor
		Channel 
			Extrapolation constant
			Value 1
			Size 3
			KeyVersion 2
			Key 0
				Frame 50
				Value 1
				RHandleX 50.25
				RHandleY 1
				LHandleX 49.75
				LHandleY 1
				FrameLock yes
				DeleteLock yes
				CurveMode hermite
				CurveOrder cubic
				TangentMode smooth
				End
			Key 1
				Frame 100
				Value 1
				RHandleX 100.25
				RHandleY 1
				LHandleX 99.75
				LHandleY 1
				CurveMode hermite
				CurveOrder cubic
				TangentMode smooth
				End
			Key 2
				Frame 150
				Value 1
				RHandleX 150.25
				RHandleY 1
				LHandleX 149.75
				LHandleY 1
				FrameLock yes
				DeleteLock yes
				CurveMode hermite
				CurveOrder cubic
				TangentMode smooth
				End
			End
		ChannelEnd
	TopLevelChannel
		Channel scene
			Uncollapsed
			End
	ResultCamChannel
		Channel ResultCamera
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		ChannelEnd
MotionBlurTopChannel
		Channel motion_blur
			Uncollapsed
			End
		MotionBlurPhaseChannel
		Channel phase
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		ChannelEnd
	MotionBlurEnableChannel
		Channel enable
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		ChannelEnd
	MotionBlurShutterChannel
		Channel shutter
			Extrapolation constant
			Value 1
			Uncollapsed
			End
		ChannelEnd
	MotionBlurSamplesChannel
		Channel samples
			Extrapolation constant
			Value 5
			Uncollapsed
			End
		ChannelEnd
		DofMode no
		DofSoftness 1
		FogMode Off
		FogColour 0 0 0
		FogStart 0
		FogEnd 1
		FogRange 1
		ProjectorMotionPathMode no
		CamMotionPathMode no
		AxisMotionPathMode no
		LightMotionPathMode no
		PropScalingMode no
		SPropScalingMode yes
		YSnapMode no
		YGridSize 1
		AutoKeyMode yes
		UpdateMode yes
		InteractiveMode 0
		AutoParentMode yes
		ForceProxyUpdate yes
		UndoLevels 10
		DrawIconsMode IconsOn
		IconTransparency 0
		SchematicTransparency 0
		ClipInfo 0
		SubMenu AXIS_MENU
		ColourClamping no
		End

#
# node database
#
ConcreteFileVersion 1.5
CreationDate Mon May 16 10:00:56 2011


WorldScale 1

Node Group
	Name scene
	Number 0
	Child 2
	Child 3
	Child 4
	MotionPath no
	ShadowCaster yes
	ShadowReceiver yes
	ShadowOnly no
	PosX 0
	PosY 0
	Flags SCHEMATIC_HIDDEN
	IsLocked no
	OutputsSize 1
	0
	Specifics
	{
	}
End
Node Camera
	Name DefaultCam
	Number 2
	MotionPath no
	ShadowCaster yes
	ShadowReceiver yes
	ShadowOnly no
	PosX -530
	PosY 258
	IsLocked no
	OutputsSize 0
	Specifics
	{
		CamChannel
		{
		Channel position/x
			Extrapolation constant
			Value 0.000000000
			End
		Channel position/y
			Extrapolation constant
			Value 0.000000000
			End
		Channel position/z
			Extrapolation constant
			Value 2137.537109375
			End
		Channel speed
			Extrapolation constant
			Value 0
			End
		Channel interest/x
			Extrapolation constant
			Value 0.000000000
			End
		Channel interest/y
			Extrapolation constant
			Value 0.000000000
			End
		Channel interest/z
			Extrapolation constant
			Value 0.000000000
			End
		Channel int_speed
			Extrapolation constant
			Value 0
			End
		Channel rotation/x
			Extrapolation constant
			Value 0.000000000
			End
		Channel rotation/y
			Extrapolation constant
			Value 0.000000000
			End
		Channel rotation/z
			Extrapolation constant
			Value 0.000000000
			End
		Channel roll
			Extrapolation constant
			Value 0.000000000
			End
		Channel fov
			Extrapolation constant
			Value 40.000000000
			End
		Channel near
			Extrapolation constant
			Value 1
			End
		Channel far
			Extrapolation constant
			Value 10000
			End
		Channel distance
			Extrapolation constant
			Value 2137.54004
			End
		Channel lens_distortion/x
			Extrapolation constant
			Value 0
			End
		Channel lens_distortion/y
			Extrapolation constant
			Value 0
			End
		Channel lens_distortion/magnitude
			Extrapolation constant
			Value 0
			End
		Channel lens_distortion/adjustment
			Extrapolation constant
			Value 0
			End
		Channel lens_distortion/anamorph
			Extrapolation constant
			Value 1
			End
		ChannelEnd
		}
		CamLensFitRes 0
		CamLensFilter 1
		CamLensMode 0
		CamMotionPathMode no
		CamMotionPath
		{
		Path pos_path
			Dimension 3
			Closed no
			Size 0
			End

		Path poi_path
			Dimension 3
			Closed no
			Size 0
			End

		}
		Origin 0
		CamIndex 0
		CamPhysicalParameters
		PhysicalCameraEnabled no
		FStop FStop_1
		Film_Type 35mm_Full_Frame
	}
End
Node Camera
	Name WorkingCam
	Number 3
	MotionPath no
	ShadowCaster yes
	ShadowReceiver yes
	ShadowOnly no
	PosX -394
	PosY 258
	Flags HIDDEN&SCHEMATIC_HIDDEN
	IsLocked no
	OutputsSize 0
	Specifics
	{
		CamChannel
		{
		Channel position/x
			Extrapolation constant
			Value 0.000000000
			End
		Channel position/y
			Extrapolation constant
			Value 0.000000000
			End
		Channel position/z
			Extrapolation constant
			Value 2137.537109375
			End
		Channel speed
			Extrapolation constant
			Value 0
			End
		Channel interest/x
			Extrapolation constant
			Value 0.000000000
			End
		Channel interest/y
			Extrapolation constant
			Value 0.000000000
			End
		Channel interest/z
			Extrapolation constant
			Value 0.000000000
			End
		Channel int_speed
			Extrapolation constant
			Value 0
			End
		Channel rotation/x
			Extrapolation constant
			Value 0.000000000
			End
		Channel rotation/y
			Extrapolation constant
			Value 0.000000000
			End
		Channel rotation/z
			Extrapolation constant
			Value 0.000000000
			End
		Channel roll
			Extrapolation constant
			Value 0.000000000
			End
		Channel fov
			Extrapolation constant
			Value 40.000000000
			End
		Channel near
			Extrapolation constant
			Value 1
			End
		Channel far
			Extrapolation constant
			Value 10000
			End
		Channel distance
			Extrapolation constant
			Value 2137.54004
			End
		Channel lens_distortion/x
			Extrapolation constant
			Value 0
			End
		Channel lens_distortion/y
			Extrapolation constant
			Value 0
			End
		Channel lens_distortion/magnitude
			Extrapolation constant
			Value 0
			End
		Channel lens_distortion/adjustment
			Extrapolation constant
			Value 0
			End
		Channel lens_distortion/anamorph
			Extrapolation constant
			Value 1
			End
		ChannelEnd
		}
		CamLensFitRes 0
		CamLensFilter 1
		CamLensMode 0
		CamMotionPathMode no
		CamMotionPath
		{
		Path pos_path
			Dimension 3
			Closed no
			Size 0
			End

		Path poi_path
			Dimension 3
			Closed no
			Size 0
			End

		}
		Origin 0
		CamIndex 1000004
		CamPhysicalParameters
		PhysicalCameraEnabled no
		FStop FStop_1
		Film_Type 35mm_Full_Frame
	}
End
Node Axis
	Name axis1
	Number 4
	MotionPath no
	ShadowCaster yes
	ShadowReceiver yes
	ShadowOnly no
	PosX -50
	PosY 19
	IsLocked no
	OutputsSize 1
	0
	Specifics
	{
		Channel position/x
			Extrapolation linear
			Value 0
			Size 200
			KeyVersion 2
			Key 0
				Frame 1
				Value -459
				RHandleX 1.33333337
				RHandleY -459
				LHandleX 0.666666627
				LHandleY -459
				CurveMode hermite
				CurveOrder linear
				End
			Key 1
				Frame 2
				Value -426.528015
				RHandleX 2.33333325
				RHandleY -415.703857
				LHandleX 1.66666663
				LHandleY -437.352173
				CurveMode hermite
				CurveOrder linear
				End
			Key 2
				Frame 3
				Value -394.054993
				RHandleX 3.33333325
				RHandleY -383.230835
				LHandleX 2.66666675
				LHandleY -404.87915
				CurveMode hermite
				CurveOrder linear
				End
			Key 3
				Frame 4
				Value -361.583008
				RHandleX 4.33333349
				RHandleY -350.759003
				LHandleX 3.66666675
				LHandleY -372.407013
				CurveMode hermite
				CurveOrder linear
				End
			Key 4
				Frame 5
				Value -329.110992
				RHandleX 5.33333349
				RHandleY -318.286835
				LHandleX 4.66666651
				LHandleY -339.93515
				CurveMode hermite
				CurveOrder linear
				End
			Key 5
				Frame 6
				Value -296.638
				RHandleX 6.33333349
				RHandleY -285.813843
				LHandleX 5.66666651
				LHandleY -307.462158
				CurveMode hermite
				CurveOrder linear
				End
			Key 6
				Frame 7
				Value -264.165985
				RHandleX 7.33333349
				RHandleY -253.34198
				LHandleX 6.66666651
				LHandleY -274.98999
				CurveMode hermite
				CurveOrder linear
				End
			Key 7
				Frame 8
				Value -231.694
				RHandleX 8.33333302
				RHandleY -220.869827
				LHandleX 7.66666651
				LHandleY -242.518158
				CurveMode hermite
				CurveOrder linear
				End
			Key 8
				Frame 9
				Value -199.220993
				RHandleX 9.33333302
				RHandleY -188.39682
				LHandleX 8.66666698
				LHandleY -210.045166
				CurveMode hermite
				CurveOrder linear
				End
			Key 9
				Frame 10
				Value -166.748993
				RHandleX 10.333333
				RHandleY -155.924988
				LHandleX 9.66666698
				LHandleY -177.572998
				CurveMode hermite
				CurveOrder linear
				End
			Key 10
				Frame 11
				Value -134.276993
				RHandleX 11.333333
				RHandleY -123.452827
				LHandleX 10.666667
				LHandleY -145.101166
				CurveMode hermite
				CurveOrder linear
				End
			Key 11
				Frame 12
				Value -101.804001
				RHandleX 12.333333
				RHandleY -90.9798203
				LHandleX 11.666667
				LHandleY -112.628181
				CurveMode hermite
				CurveOrder linear
				End
			Key 12
				Frame 13
				Value -69.3319016
				RHandleX 13.333333
				RHandleY -58.5078163
				LHandleX 12.666667
				LHandleY -80.155983
				CurveMode hermite
				CurveOrder linear
				End
			Key 13
				Frame 14
				Value -36.8595009
				RHandleX 14.333333
				RHandleY -26.0353851
				LHandleX 13.666667
				LHandleY -47.6836166
				CurveMode hermite
				CurveOrder linear
				End
			Key 14
				Frame 15
				Value -4.38720989
				RHandleX 15.333333
				RHandleY 6.4368906
				LHandleX 14.666667
				LHandleY -15.2113104
				CurveMode hermite
				CurveOrder linear
				End
			Key 15
				Frame 16
				Value 28.0851002
				RHandleX 16.333334
				RHandleY 38.9092178
				LHandleX 15.666667
				LHandleY 17.2609825
				CurveMode hermite
				CurveOrder linear
				End
			Key 16
				Frame 17
				Value 60.5574989
				RHandleX 17.333334
				RHandleY 71.3816147
				LHandleX 16.666666
				LHandleY 49.7333832
				CurveMode hermite
				CurveOrder linear
				End
			Key 17
				Frame 18
				Value 93.0298004
				RHandleX 18.333334
				RHandleY 103.853882
				LHandleX 17.666666
				LHandleY 82.205719
				CurveMode hermite
				CurveOrder linear
				End
			Key 18
				Frame 19
				Value 125.501999
				RHandleX 19.333334
				RHandleY 136.326202
				LHandleX 18.666666
				LHandleY 114.677795
				CurveMode hermite
				CurveOrder linear
				End
			Key 19
				Frame 20
				Value 157.975006
				RHandleX 20.333334
				RHandleY 168.799179
				LHandleX 19.666666
				LHandleY 147.150833
				CurveMode hermite
				CurveOrder linear
				End
			Key 20
				Frame 21
				Value 190.447006
				RHandleX 21.333334
				RHandleY 201.271011
				LHandleX 20.666666
				LHandleY 179.623001
				CurveMode hermite
				CurveOrder linear
				End
			Key 21
				Frame 22
				Value 222.919006
				RHandleX 22.333334
				RHandleY 228.268341
				LHandleX 21.666666
				LHandleY 217.569672
				CurveMode hermite
				CurveOrder linear
				End
			Key 22
				Frame 23
				Value 222.542999
				RHandleX 23.333334
				RHandleY 222.345673
				LHandleX 22.666666
				LHandleY 222.740326
				CurveMode hermite
				CurveOrder linear
				End
			Key 23
				Frame 24
				Value 221.735001
				RHandleX 24.333334
				RHandleY 221.395508
				LHandleX 23.666666
				LHandleY 222.074493
				CurveMode hermite
				CurveOrder linear
				End
			Key 24
				Frame 25
				Value 220.505997
				RHandleX 25.333334
				RHandleY 220.028
				LHandleX 24.666666
				LHandleY 220.983994
				CurveMode hermite
				CurveOrder linear
				End
			Key 25
				Frame 26
				Value 218.867004
				RHandleX 26.333334
				RHandleY 218.254333
				LHandleX 25.666666
				LHandleY 219.479675
				CurveMode hermite
				CurveOrder linear
				End
			Key 26
				Frame 27
				Value 216.830002
				RHandleX 27.333334
				RHandleY 216.086502
				LHandleX 26.666666
				LHandleY 217.573502
				CurveMode hermite
				CurveOrder linear
				End
			Key 27
				Frame 28
				Value 214.406006
				RHandleX 28.333334
				RHandleY 213.535675
				LHandleX 27.666666
				LHandleY 215.276337
				CurveMode hermite
				CurveOrder linear
				End
			Key 28
				Frame 29
				Value 211.608002
				RHandleX 29.333334
				RHandleY 210.614502
				LHandleX 28.666666
				LHandleY 212.601501
				CurveMode hermite
				CurveOrder linear
				End
			Key 29
				Frame 30
				Value 208.445007
				RHandleX 30.333334
				RHandleY 207.332169
				LHandleX 29.666666
				LHandleY 209.557846
				CurveMode hermite
				CurveOrder linear
				End
			Key 30
				Frame 31
				Value 204.931
				RHandleX 31.333334
				RHandleY 203.702667
				LHandleX 30.666666
				LHandleY 206.159332
				CurveMode hermite
				CurveOrder linear
				End
			Key 31
				Frame 32
				Value 201.074997
				RHandleX 32.3333321
				RHandleY 199.734833
				LHandleX 31.666666
				LHandleY 202.415161
				CurveMode hermite
				CurveOrder linear
				End
			Key 32
				Frame 33
				Value 196.889999
				RHandleX 33.3333321
				RHandleY 195.442001
				LHandleX 32.6666679
				LHandleY 198.337997
				CurveMode hermite
				CurveOrder linear
				End
			Key 33
				Frame 34
				Value 192.386993
				RHandleX 34.3333321
				RHandleY 190.834991
				LHandleX 33.6666679
				LHandleY 193.938995
				CurveMode hermite
				CurveOrder linear
				End
			Key 34
				Frame 35
				Value 187.578003
				RHandleX 35.3333321
				RHandleY 185.925674
				LHandleX 34.6666679
				LHandleY 189.230331
				CurveMode hermite
				CurveOrder linear
				End
			Key 35
				Frame 36
				Value 182.473007
				RHandleX 36.3333321
				RHandleY 180.724182
				LHandleX 35.6666679
				LHandleY 184.221832
				CurveMode hermite
				CurveOrder linear
				End
			Key 36
				Frame 37
				Value 177.085007
				RHandleX 37.3333321
				RHandleY 175.243668
				LHandleX 36.6666679
				LHandleY 178.926346
				CurveMode hermite
				CurveOrder linear
				End
			Key 37
				Frame 38
				Value 171.425003
				RHandleX 38.3333321
				RHandleY 169.494675
				LHandleX 37.6666679
				LHandleY 173.355331
				CurveMode hermite
				CurveOrder linear
				End
			Key 38
				Frame 39
				Value 165.503006
				RHandleX 39.3333321
				RHandleY 163.487671
				LHandleX 38.6666679
				LHandleY 167.518341
				CurveMode hermite
				CurveOrder linear
				End
			Key 39
				Frame 40
				Value 159.332993
				RHandleX 40.3333321
				RHandleY 157.236496
				LHandleX 39.6666679
				LHandleY 161.429489
				CurveMode hermite
				CurveOrder linear
				End
			Key 40
				Frame 41
				Value 152.923996
				RHandleX 41.3333321
				RHandleY 150.750168
				LHandleX 40.6666679
				LHandleY 155.097824
				CurveMode hermite
				CurveOrder linear
				End
			Key 41
				Frame 42
				Value 146.289993
				RHandleX 42.3333321
				RHandleY 144.042664
				LHandleX 41.6666679
				LHandleY 148.537323
				CurveMode hermite
				CurveOrder linear
				End
			Key 42
				Frame 43
				Value 139.440002
				RHandleX 43.3333321
				RHandleY 137.122665
				LHandleX 42.6666679
				LHandleY 141.757339
				CurveMode hermite
				CurveOrder linear
				End
			Key 43
				Frame 44
				Value 132.386002
				RHandleX 44.3333321
				RHandleY 130.002838
				LHandleX 43.6666679
				LHandleY 134.769165
				CurveMode hermite
				CurveOrder linear
				End
			Key 44
				Frame 45
				Value 125.140999
				RHandleX 45.3333321
				RHandleY 122.695831
				LHandleX 44.6666679
				LHandleY 127.586166
				CurveMode hermite
				CurveOrder linear
				End
			Key 45
				Frame 46
				Value 117.714996
				RHandleX 46.3333321
				RHandleY 115.211327
				LHandleX 45.6666679
				LHandleY 120.218666
				CurveMode hermite
				CurveOrder linear
				End
			Key 46
				Frame 47
				Value 110.119003
				RHandleX 47.3333321
				RHandleY 107.560837
				LHandleX 46.6666679
				LHandleY 112.67717
				CurveMode hermite
				CurveOrder linear
				End
			Key 47
				Frame 48
				Value 102.365997
				RHandleX 48.3333321
				RHandleY 99.7571793
				LHandleX 47.6666679
				LHandleY 104.974815
				CurveMode hermite
				CurveOrder linear
				End
			Key 48
				Frame 49
				Value 94.4661026
				RHandleX 49.3333321
				RHandleY 91.8103714
				LHandleX 48.6666679
				LHandleY 97.1218338
				CurveMode hermite
				CurveOrder linear
				End
			Key 49
				Frame 50
				Value 86.4316025
				RHandleX 50.3333321
				RHandleY 83.7328339
				LHandleX 49.6666679
				LHandleY 89.1303711
				CurveMode hermite
				CurveOrder linear
				End
			Key 50
				Frame 51
				Value 78.2734985
				RHandleX 51.3333321
				RHandleY 75.5354614
				LHandleX 50.6666679
				LHandleY 81.0115356
				CurveMode hermite
				CurveOrder linear
				End
			Key 51
				Frame 52
				Value 70.0034027
				RHandleX 52.3333321
				RHandleY 67.2299347
				LHandleX 51.6666679
				LHandleY 72.7768707
				CurveMode hermite
				CurveOrder linear
				End
			Key 52
				Frame 53
				Value 61.6327019
				RHandleX 53.3333321
				RHandleY 58.8276024
				LHandleX 52.6666679
				LHandleY 64.4378052
				CurveMode hermite
				CurveOrder linear
				End
			Key 53
				Frame 54
				Value 53.1727982
				RHandleX 54.3333321
				RHandleY 50.3398972
				LHandleX 53.6666679
				LHandleY 56.0056992
				CurveMode hermite
				CurveOrder linear
				End
			Key 54
				Frame 55
				Value 44.6352997
				RHandleX 55.3333321
				RHandleY 41.7784004
				LHandleX 54.6666679
				LHandleY 47.4921989
				CurveMode hermite
				CurveOrder linear
				End
			Key 55
				Frame 56
				Value 36.0313988
				RHandleX 56.3333321
				RHandleY 33.1542969
				LHandleX 55.6666679
				LHandleY 38.9085007
				CurveMode hermite
				CurveOrder linear
				End
			Key 56
				Frame 57
				Value 27.3726997
				RHandleX 57.3333321
				RHandleY 24.4792156
				LHandleX 56.6666679
				LHandleY 30.2661839
				CurveMode hermite
				CurveOrder linear
				End
			Key 57
				Frame 58
				Value 18.6704998
				RHandleX 58.3333321
				RHandleY 15.7644587
				LHandleX 57.6666679
				LHandleY 21.5765419
				CurveMode hermite
				CurveOrder linear
				End
			Key 58
				Frame 59
				Value 9.93645
				RHandleX 59.3333321
				RHandleY 7.02167511
				LHandleX 58.6666679
				LHandleY 12.8512249
				CurveMode hermite
				CurveOrder linear
				End
			Key 59
				Frame 60
				Value 1.18184996
				RHandleX 60.3333321
				RHandleY -1.73786652
				LHandleX 59.6666679
				LHandleY 4.10156631
				CurveMode hermite
				CurveOrder linear
				End
			Key 60
				Frame 61
				Value -7.58185005
				RHandleX 61.3333321
				RHandleY -10.5026922
				LHandleX 60.6666679
				LHandleY -4.66100836
				CurveMode hermite
				CurveOrder linear
				End
			Key 61
				Frame 62
				Value -16.3432007
				RHandleX 62.3333321
				RHandleY -19.261343
				LHandleX 61.6666679
				LHandleY -13.4250593
				CurveMode hermite
				CurveOrder linear
				End
			Key 62
				Frame 63
				Value -25.0907001
				RHandleX 63.3333321
				RHandleY -28.0023327
				LHandleX 62.6666679
				LHandleY -22.1790676
				CurveMode hermite
				CurveOrder linear
				End
			Key 63
				Frame 64
				Value -33.8129997
				RHandleX 64.3333359
				RHandleY -36.7142982
				LHandleX 63.6666679
				LHandleY -30.9116993
				CurveMode hermite
				CurveOrder linear
				End
			Key 64
				Frame 65
				Value -42.4985008
				RHandleX 65.3333359
				RHandleY -45.3856659
				LHandleX 64.6666641
				LHandleY -39.6113358
				CurveMode hermite
				CurveOrder linear
				End
			Key 65
				Frame 66
				Value -51.1360016
				RHandleX 66.3333359
				RHandleY -54.0052528
				LHandleX 65.6666641
				LHandleY -48.2667503
				CurveMode hermite
				CurveOrder linear
				End
			Key 66
				Frame 67
				Value -59.7140007
				RHandleX 67.3333359
				RHandleY -62.5614853
				LHandleX 66.6666641
				LHandleY -56.8665161
				CurveMode hermite
				CurveOrder linear
				End
			Key 67
				Frame 68
				Value -68.2209015
				RHandleX 68.3333359
				RHandleY -71.0428009
				LHandleX 67.6666641
				LHandleY -65.3990021
				CurveMode hermite
				CurveOrder linear
				End
			Key 68
				Frame 69
				Value -76.645401
				RHandleX 69.3333359
				RHandleY -79.4378967
				LHandleX 68.6666641
				LHandleY -73.8529053
				CurveMode hermite
				CurveOrder linear
				End
			Key 69
				Frame 70
				Value -84.9758987
				RHandleX 70.3333359
				RHandleY -87.735199
				LHandleX 69.6666641
				LHandleY -82.2165985
				CurveMode hermite
				CurveOrder linear
				End
			Key 70
				Frame 71
				Value -93.2012024
				RHandleX 71.3333359
				RHandleY -95.9235535
				LHandleX 70.6666641
				LHandleY -90.4788513
				CurveMode hermite
				CurveOrder linear
				End
			Key 71
				Frame 72
				Value -101.309998
				RHandleX 72.3333359
				RHandleY -103.991463
				LHandleX 71.6666641
				LHandleY -98.6285324
				CurveMode hermite
				CurveOrder linear
				End
			Key 72
				Frame 73
				Value -109.290001
				RHandleX 73.3333359
				RHandleY -111.926834
				LHandleX 72.6666641
				LHandleY -106.653168
				CurveMode hermite
				CurveOrder linear
				End
			Key 73
				Frame 74
				Value -117.130997
				RHandleX 74.3333359
				RHandleY -119.71933
				LHandleX 73.6666641
				LHandleY -114.542664
				CurveMode hermite
				CurveOrder linear
				End
			Key 74
				Frame 75
				Value -124.82
				RHandleX 75.3333359
				RHandleY -127.356003
				LHandleX 74.6666641
				LHandleY -122.283997
				CurveMode hermite
				CurveOrder linear
				End
			Key 75
				Frame 76
				Value -132.347
				RHandleX 76.3333359
				RHandleY -134.826996
				LHandleX 75.6666641
				LHandleY -129.867004
				CurveMode hermite
				CurveOrder linear
				End
			Key 76
				Frame 77
				Value -139.699997
				RHandleX 77.3333359
				RHandleY -142.120163
				LHandleX 76.6666641
				LHandleY -137.279831
				CurveMode hermite
				CurveOrder linear
				End
			Key 77
				Frame 78
				Value -146.867996
				RHandleX 78.3333359
				RHandleY -149.224503
				LHandleX 77.6666641
				LHandleY -144.51149
				CurveMode hermite
				CurveOrder linear
				End
			Key 78
				Frame 79
				Value -153.839005
				RHandleX 79.3333359
				RHandleY -156.127838
				LHandleX 78.6666641
				LHandleY -151.550171
				CurveMode hermite
				CurveOrder linear
				End
			Key 79
				Frame 80
				Value -160.600998
				RHandleX 80.3333359
				RHandleY -162.818497
				LHandleX 79.6666641
				LHandleY -158.383499
				CurveMode hermite
				CurveOrder linear
				End
			Key 80
				Frame 81
				Value -167.143997
				RHandleX 81.3333359
				RHandleY -169.286499
				LHandleX 80.6666641
				LHandleY -165.001495
				CurveMode hermite
				CurveOrder linear
				End
			Key 81
				Frame 82
				Value -173.455994
				RHandleX 82.3333359
				RHandleY -175.519485
				LHandleX 81.6666641
				LHandleY -171.392502
				CurveMode hermite
				CurveOrder linear
				End
			Key 82
				Frame 83
				Value -179.524994
				RHandleX 83.3333359
				RHandleY -181.505661
				LHandleX 82.6666641
				LHandleY -177.544327
				CurveMode hermite
				CurveOrder linear
				End
			Key 83
				Frame 84
				Value -185.339996
				RHandleX 84.3333359
				RHandleY -187.233994
				LHandleX 83.6666641
				LHandleY -183.445999
				CurveMode hermite
				CurveOrder linear
				End
			Key 84
				Frame 85
				Value -190.889008
				RHandleX 85.3333359
				RHandleY -192.692673
				LHandleX 84.6666641
				LHandleY -189.085342
				CurveMode hermite
				CurveOrder linear
				End
			Key 85
				Frame 86
				Value -196.162003
				RHandleX 86.3333359
				RHandleY -197.871506
				LHandleX 85.6666641
				LHandleY -194.452499
				CurveMode hermite
				CurveOrder linear
				End
			Key 86
				Frame 87
				Value -201.145996
				RHandleX 87.3333359
				RHandleY -202.757324
				LHandleX 86.6666641
				LHandleY -199.534668
				CurveMode hermite
				CurveOrder linear
				End
			Key 87
				Frame 88
				Value -205.830002
				RHandleX 88.3333359
				RHandleY -207.339661
				LHandleX 87.6666641
				LHandleY -204.320343
				CurveMode hermite
				CurveOrder linear
				End
			Key 88
				Frame 89
				Value -210.203995
				RHandleX 89.3333359
				RHandleY -211.607986
				LHandleX 88.6666641
				LHandleY -208.800003
				CurveMode hermite
				CurveOrder linear
				End
			Key 89
				Frame 90
				Value -214.253998
				RHandleX 90.3333359
				RHandleY -215.548325
				LHandleX 89.6666641
				LHandleY -212.959671
				CurveMode hermite
				CurveOrder linear
				End
			Key 90
				Frame 91
				Value -217.970001
				RHandleX 91.3333359
				RHandleY -219.151169
				LHandleX 90.6666641
				LHandleY -216.788834
				CurveMode hermite
				CurveOrder linear
				End
			Key 91
				Frame 92
				Value -221.341003
				RHandleX 92.3333359
				RHandleY -222.405167
				LHandleX 91.6666641
				LHandleY -220.27684
				CurveMode hermite
				CurveOrder linear
				End
			Key 92
				Frame 93
				Value -224.354996
				RHandleX 93.3333359
				RHandleY -225.298157
				LHandleX 92.6666641
				LHandleY -223.411835
				CurveMode hermite
				CurveOrder linear
				End
			Key 93
				Frame 94
				Value -227
				RHandleX 94.3333359
				RHandleY -227.440826
				LHandleX 93.6666641
				LHandleY -226.559174
				CurveMode hermite
				CurveOrder linear
				End
			Key 94
				Frame 95
				Value -227
				RHandleX 95.3333359
				RHandleY -227
				LHandleX 94.6666641
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 95
				Frame 96
				Value -227
				RHandleX 96.3333359
				RHandleY -227
				LHandleX 95.6666641
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 96
				Frame 97
				Value -227
				RHandleX 97.3333359
				RHandleY -227
				LHandleX 96.6666641
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 97
				Frame 98
				Value -227
				RHandleX 98.3333359
				RHandleY -227
				LHandleX 97.6666641
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 98
				Frame 99
				Value -227
				RHandleX 99.3333359
				RHandleY -227
				LHandleX 98.6666641
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 99
				Frame 100
				Value -227
				RHandleX 100.333336
				RHandleY -227
				LHandleX 99.6666641
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 100
				Frame 101
				Value -227
				RHandleX 101.333336
				RHandleY -227
				LHandleX 100.666664
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 101
				Frame 102
				Value -227
				RHandleX 102.333336
				RHandleY -227
				LHandleX 101.666664
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 102
				Frame 103
				Value -227
				RHandleX 103.333336
				RHandleY -227
				LHandleX 102.666664
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 103
				Frame 104
				Value -227
				RHandleX 104.333336
				RHandleY -227
				LHandleX 103.666664
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 104
				Frame 105
				Value -227
				RHandleX 105.333336
				RHandleY -227
				LHandleX 104.666664
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 105
				Frame 106
				Value -227
				RHandleX 106.333336
				RHandleY -227
				LHandleX 105.666664
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 106
				Frame 107
				Value -227
				RHandleX 107.333336
				RHandleY -227
				LHandleX 106.666664
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 107
				Frame 108
				Value -227
				RHandleX 108.333336
				RHandleY -227
				LHandleX 107.666664
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 108
				Frame 109
				Value -227
				RHandleX 109.333336
				RHandleY -227
				LHandleX 108.666664
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 109
				Frame 110
				Value -227
				RHandleX 110.333336
				RHandleY -227
				LHandleX 109.666664
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 110
				Frame 111
				Value -227
				RHandleX 111.333336
				RHandleY -227
				LHandleX 110.666664
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 111
				Frame 112
				Value -227
				RHandleX 112.333336
				RHandleY -227
				LHandleX 111.666664
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 112
				Frame 113
				Value -227
				RHandleX 113.333336
				RHandleY -227
				LHandleX 112.666664
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 113
				Frame 114
				Value -227
				RHandleX 114.333336
				RHandleY -227
				LHandleX 113.666664
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 114
				Frame 115
				Value -227
				RHandleX 115.333336
				RHandleY -227
				LHandleX 114.666664
				LHandleY -227
				CurveMode hermite
				CurveOrder linear
				End
			Key 115
				Frame 116
				Value -227
				RHandleX 116.333336
				RHandleY -188.960159
				LHandleX 115.666664
				LHandleY -265.039856
				CurveMode hermite
				CurveOrder linear
				End
			Key 116
				Frame 117
				Value 1.23907006
				RHandleX 117.333336
				RHandleY 41.6047859
				LHandleX 116.666664
				LHandleY -39.1266479
				CurveMode hermite
				CurveOrder linear
				End
			Key 117
				Frame 118
				Value 15.1942997
				RHandleX 118.333336
				RHandleY 19.8018208
				LHandleX 117.666664
				LHandleY 10.5867786
				CurveMode hermite
				CurveOrder linear
				End
			Key 118
				Frame 119
				Value 28.8841991
				RHandleX 119.333336
				RHandleY 33.4013176
				LHandleX 118.666664
				LHandleY 24.3670826
				CurveMode hermite
				CurveOrder linear
				End
			Key 119
				Frame 120
				Value 42.2970009
				RHandleX 120.333336
				RHandleY 46.7198029
				LHandleX 119.666664
				LHandleY 37.8741989
				CurveMode hermite
				CurveOrder linear
				End
			Key 120
				Frame 121
				Value 55.4210014
				RHandleX 121.333336
				RHandleY 59.7456017
				LHandleX 120.666664
				LHandleY 51.0964012
				CurveMode hermite
				CurveOrder linear
				End
			Key 121
				Frame 122
				Value 68.2445984
				RHandleX 122.333336
				RHandleY 72.4671173
				LHandleX 121.666664
				LHandleY 64.0220795
				CurveMode hermite
				CurveOrder linear
				End
			Key 122
				Frame 123
				Value 80.7561035
				RHandleX 123.333336
				RHandleY 84.8726349
				LHandleX 122.666664
				LHandleY 76.6395721
				CurveMode hermite
				CurveOrder linear
				End
			Key 123
				Frame 124
				Value 92.9438019
				RHandleX 124.333336
				RHandleY 96.9504471
				LHandleX 123.666664
				LHandleY 88.9371567
				CurveMode hermite
				CurveOrder linear
				End
			Key 124
				Frame 125
				Value 104.795998
				RHandleX 125.333336
				RHandleY 108.688866
				LHandleX 124.666664
				LHandleY 100.90313
				CurveMode hermite
				CurveOrder linear
				End
			Key 125
				Frame 126
				Value 116.301003
				RHandleX 126.333336
				RHandleY 120.076172
				LHandleX 125.666664
				LHandleY 112.525833
				CurveMode hermite
				CurveOrder linear
				End
			Key 126
				Frame 127
				Value 127.446999
				RHandleX 127.333336
				RHandleY 131.100662
				LHandleX 126.666664
				LHandleY 123.793335
				CurveMode hermite
				CurveOrder linear
				End
			Key 127
				Frame 128
				Value 138.223007
				RHandleX 128.333328
				RHandleY 141.751175
				LHandleX 127.666664
				LHandleY 134.694839
				CurveMode hermite
				CurveOrder linear
				End
			Key 128
				Frame 129
				Value 148.615997
				RHandleX 129.333328
				RHandleY 152.014832
				LHandleX 128.666672
				LHandleY 145.217163
				CurveMode hermite
				CurveOrder linear
				End
			Key 129
				Frame 130
				Value 158.615997
				RHandleX 130.333328
				RHandleY 161.881668
				LHandleX 129.666672
				LHandleY 155.350327
				CurveMode hermite
				CurveOrder linear
				End
			Key 130
				Frame 131
				Value 168.210007
				RHandleX 131.333328
				RHandleY 171.338501
				LHandleX 130.666672
				LHandleY 165.081512
				CurveMode hermite
				CurveOrder linear
				End
			Key 131
				Frame 132
				Value 177.386993
				RHandleX 132.333328
				RHandleY 180.374496
				LHandleX 131.666672
				LHandleY 174.39949
				CurveMode hermite
				CurveOrder linear
				End
			Key 132
				Frame 133
				Value 186.134995
				RHandleX 133.333328
				RHandleY 188.977493
				LHandleX 132.666672
				LHandleY 183.292496
				CurveMode hermite
				CurveOrder linear
				End
			Key 133
				Frame 134
				Value 194.442001
				RHandleX 134.333328
				RHandleY 197.135666
				LHandleX 133.666672
				LHandleY 191.748337
				CurveMode hermite
				CurveOrder linear
				End
			Key 134
				Frame 135
				Value 202.296997
				RHandleX 135.333328
				RHandleY 204.838165
				LHandleX 134.666672
				LHandleY 199.755829
				CurveMode hermite
				CurveOrder linear
				End
			Key 135
				Frame 136
				Value 209.688995
				RHandleX 136.333328
				RHandleY 212.073502
				LHandleX 135.666672
				LHandleY 207.304489
				CurveMode hermite
				CurveOrder linear
				End
			Key 136
				Frame 137
				Value 216.604004
				RHandleX 137.333328
				RHandleY 218.827835
				LHandleX 136.666672
				LHandleY 214.380173
				CurveMode hermite
				CurveOrder linear
				End
			Key 137
				Frame 138
				Value 223.031998
				RHandleX 138.333328
				RHandleY 225.091492
				LHandleX 137.666672
				LHandleY 220.972504
				CurveMode hermite
				CurveOrder linear
				End
			Key 138
				Frame 139
				Value 228.960999
				RHandleX 139.333328
				RHandleY 230.852341
				LHandleX 138.666672
				LHandleY 227.069656
				CurveMode hermite
				CurveOrder linear
				End
			Key 139
				Frame 140
				Value 234.380005
				RHandleX 140.333328
				RHandleY 236.099167
				LHandleX 139.666672
				LHandleY 232.660843
				CurveMode hermite
				CurveOrder linear
				End
			Key 140
				Frame 141
				Value 239.276001
				RHandleX 141.333328
				RHandleY 240.819
				LHandleX 140.666672
				LHandleY 237.733002
				CurveMode hermite
				CurveOrder linear
				End
			Key 141
				Frame 142
				Value 243.638
				RHandleX 142.333328
				RHandleY 245.001175
				LHandleX 141.666672
				LHandleY 242.274826
				CurveMode hermite
				CurveOrder linear
				End
			Key 142
				Frame 143
				Value 247.455002
				RHandleX 143.333328
				RHandleY 248.634338
				LHandleX 142.666672
				LHandleY 246.275665
				CurveMode hermite
				CurveOrder linear
				End
			Key 143
				Frame 144
				Value 250.714005
				RHandleX 144.333328
				RHandleY 251.705505
				LHandleX 143.666672
				LHandleY 249.722504
				CurveMode hermite
				CurveOrder linear
				End
			Key 144
				Frame 145
				Value 253.404007
				RHandleX 145.333328
				RHandleY 254.203842
				LHandleX 144.666672
				LHandleY 252.604172
				CurveMode hermite
				CurveOrder linear
				End
			Key 145
				Frame 146
				Value 255.513
				RHandleX 146.333328
				RHandleY 256.11734
				LHandleX 145.666672
				LHandleY 254.908661
				CurveMode hermite
				CurveOrder linear
				End
			Key 146
				Frame 147
				Value 257.029999
				RHandleX 147.333328
				RHandleY 257.434814
				LHandleX 146.666672
				LHandleY 256.625183
				CurveMode hermite
				CurveOrder linear
				End
			Key 147
				Frame 148
				Value 257.941986
				RHandleX 148.333328
				RHandleY 258.143494
				LHandleX 147.666672
				LHandleY 257.740479
				CurveMode hermite
				CurveOrder linear
				End
			Key 148
				Frame 149
				Value 258.239014
				RHandleX 149.333328
				RHandleY 258.23819
				LHandleX 148.666672
				LHandleY 258.239838
				CurveMode hermite
				CurveOrder linear
				End
			Key 149
				Frame 150
				Value 257.937012
				RHandleX 150.333328
				RHandleY 257.742859
				LHandleX 149.666672
				LHandleY 258.131165
				CurveMode hermite
				CurveOrder linear
				End
			Key 150
				Frame 151
				Value 257.074005
				RHandleX 151.333328
				RHandleY 256.696838
				LHandleX 150.666672
				LHandleY 257.451172
				CurveMode hermite
				CurveOrder linear
				End
			Key 151
				Frame 152
				Value 255.673996
				RHandleX 152.333328
				RHandleY 255.12149
				LHandleX 151.666672
				LHandleY 256.226501
				CurveMode hermite
				CurveOrder linear
				End
			Key 152
				Frame 153
				Value 253.759003
				RHandleX 153.333328
				RHandleY 253.038666
				LHandleX 152.666672
				LHandleY 254.47934
				CurveMode hermite
				CurveOrder linear
				End
			Key 153
				Frame 154
				Value 251.352005
				RHandleX 154.333328
				RHandleY 250.471497
				LHandleX 153.666672
				LHandleY 252.232513
				CurveMode hermite
				CurveOrder linear
				End
			Key 154
				Frame 155
				Value 248.475998
				RHandleX 155.333328
				RHandleY 247.442657
				LHandleX 154.666672
				LHandleY 249.509338
				CurveMode hermite
				CurveOrder linear
				End
			Key 155
				Frame 156
				Value 245.151993
				RHandleX 156.333328
				RHandleY 243.973495
				LHandleX 155.666672
				LHandleY 246.33049
				CurveMode hermite
				CurveOrder linear
				End
			Key 156
				Frame 157
				Value 241.404999
				RHandleX 157.333328
				RHandleY 240.088837
				LHandleX 156.666672
				LHandleY 242.721161
				CurveMode hermite
				CurveOrder linear
				End
			Key 157
				Frame 158
				Value 237.255005
				RHandleX 158.333328
				RHandleY 235.80867
				LHandleX 157.666672
				LHandleY 238.70134
				CurveMode hermite
				CurveOrder linear
				End
			Key 158
				Frame 159
				Value 232.727005
				RHandleX 159.333328
				RHandleY 231.158173
				LHandleX 158.666672
				LHandleY 234.295837
				CurveMode hermite
				CurveOrder linear
				End
			Key 159
				Frame 160
				Value 227.841995
				RHandleX 160.333328
				RHandleY 226.158157
				LHandleX 159.666672
				LHandleY 229.525833
				CurveMode hermite
				CurveOrder linear
				End
			Key 160
				Frame 161
				Value 222.623993
				RHandleX 161.333328
				RHandleY 220.832657
				LHandleX 160.666672
				LHandleY 224.415329
				CurveMode hermite
				CurveOrder linear
				End
			Key 161
				Frame 162
				Value 217.093994
				RHandleX 162.333328
				RHandleY 215.202667
				LHandleX 161.666672
				LHandleY 218.985321
				CurveMode hermite
				CurveOrder linear
				End
			Key 162
				Frame 163
				Value 211.276001
				RHandleX 163.333328
				RHandleY 209.292328
				LHandleX 162.666672
				LHandleY 213.259674
				CurveMode hermite
				CurveOrder linear
				End
			Key 163
				Frame 164
				Value 205.192001
				RHandleX 164.333328
				RHandleY 203.123505
				LHandleX 163.666672
				LHandleY 207.260498
				CurveMode hermite
				CurveOrder linear
				End
			Key 164
				Frame 165
				Value 198.865005
				RHandleX 165.333328
				RHandleY 196.719177
				LHandleX 164.666672
				LHandleY 201.010834
				CurveMode hermite
				CurveOrder linear
				End
			Key 165
				Frame 166
				Value 192.317001
				RHandleX 166.333328
				RHandleY 190.101334
				LHandleX 165.666672
				LHandleY 194.532669
				CurveMode hermite
				CurveOrder linear
				End
			Key 166
				Frame 167
				Value 185.570999
				RHandleX 167.333328
				RHandleY 183.293167
				LHandleX 166.666672
				LHandleY 187.848831
				CurveMode hermite
				CurveOrder linear
				End
			Key 167
				Frame 168
				Value 178.649994
				RHandleX 168.333328
				RHandleY 176.31749
				LHandleX 167.666672
				LHandleY 180.982498
				CurveMode hermite
				CurveOrder linear
				End
			Key 168
				Frame 169
				Value 171.576004
				RHandleX 169.333328
				RHandleY 169.196335
				LHandleX 168.666672
				LHandleY 173.955673
				CurveMode hermite
				CurveOrder linear
				End
			Key 169
				Frame 170
				Value 164.371994
				RHandleX 170.333328
				RHandleY 161.952652
				LHandleX 169.666672
				LHandleY 166.791336
				CurveMode hermite
				CurveOrder linear
				End
			Key 170
				Frame 171
				Value 157.059998
				RHandleX 171.333328
				RHandleY 154.608658
				LHandleX 170.666672
				LHandleY 159.511337
				CurveMode hermite
				CurveOrder linear
				End
			Key 171
				Frame 172
				Value 149.664001
				RHandleX 172.333328
				RHandleY 147.188171
				LHandleX 171.666672
				LHandleY 152.139832
				CurveMode hermite
				CurveOrder linear
				End
			Key 172
				Frame 173
				Value 142.205002
				RHandleX 173.333328
				RHandleY 139.712173
				LHandleX 172.666672
				LHandleY 144.69783
				CurveMode hermite
				CurveOrder linear
				End
			Key 173
				Frame 174
				Value 134.707001
				RHandleX 174.333328
				RHandleY 132.204834
				LHandleX 173.666672
				LHandleY 137.209167
				CurveMode hermite
				CurveOrder linear
				End
			Key 174
				Frame 175
				Value 127.192001
				RHandleX 175.333328
				RHandleY 124.688004
				LHandleX 174.666672
				LHandleY 129.695999
				CurveMode hermite
				CurveOrder linear
				End
			Key 175
				Frame 176
				Value 119.682999
				RHandleX 176.333328
				RHandleY 117.184662
				LHandleX 175.666672
				LHandleY 122.181335
				CurveMode hermite
				CurveOrder linear
				End
			Key 176
				Frame 177
				Value 112.202003
				RHandleX 177.333328
				RHandleY 109.716835
				LHandleX 176.666672
				LHandleY 114.687172
				CurveMode hermite
				CurveOrder linear
				End
			Key 177
				Frame 178
				Value 104.772003
				RHandleX 178.333328
				RHandleY 102.307518
				LHandleX 177.666672
				LHandleY 107.236488
				CurveMode hermite
				CurveOrder linear
				End
			Key 178
				Frame 179
				Value 97.4151001
				RHandleX 179.333328
				RHandleY 94.9788818
				LHandleX 178.666672
				LHandleY 99.8513184
				CurveMode hermite
				CurveOrder linear
				End
			Key 179
				Frame 180
				Value 90.1547012
				RHandleX 180.333328
				RHandleY 87.7543869
				LHandleX 179.666672
				LHandleY 92.5550156
				CurveMode hermite
				CurveOrder linear
				End
			Key 180
				Frame 181
				Value 83.0131989
				RHandleX 181.333328
				RHandleY 80.6562805
				LHandleX 180.666672
				LHandleY 85.3701172
				CurveMode hermite
				CurveOrder linear
				End
			Key 181
				Frame 182
				Value 76.0131989
				RHandleX 182.333328
				RHandleY 73.7071991
				LHandleX 181.666672
				LHandleY 78.3191986
				CurveMode hermite
				CurveOrder linear
				End
			Key 182
				Frame 183
				Value 69.1772003
				RHandleX 183.333328
				RHandleY 66.9296646
				LHandleX 182.666672
				LHandleY 71.424736
				CurveMode hermite
				CurveOrder linear
				End
			Key 183
				Frame 184
				Value 62.5279999
				RHandleX 184.333328
				RHandleY 60.3464813
				LHandleX 183.666672
				LHandleY 64.7095184
				CurveMode hermite
				CurveOrder linear
				End
			Key 184
				Frame 185
				Value 56.0881004
				RHandleX 185.333328
				RHandleY 53.9801331
				LHandleX 184.666672
				LHandleY 58.1960678
				CurveMode hermite
				CurveOrder linear
				End
			Key 185
				Frame 186
				Value 49.8801994
				RHandleX 186.333328
				RHandleY 47.8533325
				LHandleX 185.666672
				LHandleY 51.9070663
				CurveMode hermite
				CurveOrder linear
				End
			Key 186
				Frame 187
				Value 43.926899
				RHandleX 187.333328
				RHandleY 41.9886665
				LHandleX 186.666672
				LHandleY 45.8651314
				CurveMode hermite
				CurveOrder linear
				End
			Key 187
				Frame 188
				Value 38.2508011
				RHandleX 188.333328
				RHandleY 36.4087524
				LHandleX 187.666672
				LHandleY 40.0928497
				CurveMode hermite
				CurveOrder linear
				End
			Key 188
				Frame 189
				Value 32.8745995
				RHandleX 189.333328
				RHandleY 31.136282
				LHandleX 188.666672
				LHandleY 34.612915
				CurveMode hermite
				CurveOrder linear
				End
			Key 189
				Frame 190
				Value 27.8209
				RHandleX 190.333328
				RHandleY 26.1938667
				LHandleX 189.666672
				LHandleY 29.4479332
				CurveMode hermite
				CurveOrder linear
				End
			Key 190
				Frame 191
				Value 23.1124001
				RHandleX 191.333328
				RHandleY 21.604166
				LHandleX 190.666672
				LHandleY 24.6206341
				CurveMode hermite
				CurveOrder linear
				End
			Key 191
				Frame 192
				Value 18.7714996
				RHandleX 192.333328
				RHandleY 17.3896332
				LHandleX 191.666672
				LHandleY 20.1533661
				CurveMode hermite
				CurveOrder linear
				End
			Key 192
				Frame 193
				Value 14.8212004
				RHandleX 193.333328
				RHandleY 13.5732508
				LHandleX 192.666672
				LHandleY 16.0691509
				CurveMode hermite
				CurveOrder linear
				End
			Key 193
				Frame 194
				Value 11.2838001
				RHandleX 194.333328
				RHandleY 10.1772633
				LHandleX 193.666672
				LHandleY 12.390337
				CurveMode hermite
				CurveOrder linear
				End
			Key 194
				Frame 195
				Value 8.18198013
				RHandleX 195.333328
				RHandleY 7.22443485
				LHandleX 194.666672
				LHandleY 9.13952541
				CurveMode hermite
				CurveOrder linear
				End
			Key 195
				Frame 196
				Value 5.53852987
				RHandleX 196.333328
				RHandleY 4.73752975
				LHandleX 195.666672
				LHandleY 6.33952999
				CurveMode hermite
				CurveOrder linear
				End
			Key 196
				Frame 197
				Value 3.3759799
				RHandleX 197.333328
				RHandleY 2.7390449
				LHandleX 196.666672
				LHandleY 4.01291513
				CurveMode hermite
				CurveOrder linear
				End
			Key 197
				Frame 198
				Value 1.71692002
				RHandleX 198.333328
				RHandleY 1.25159752
				LHandleX 197.666672
				LHandleY 2.18224263
				CurveMode hermite
				CurveOrder linear
				End
			Key 198
				Frame 199
				Value 0.584044993
				RHandleX 199.333328
				RHandleY 0.297891647
				LHandleX 198.666672
				LHandleY 0.870198309
				CurveMode hermite
				CurveOrder linear
				End
			Key 199
				Frame 200
				Value 0
				RHandleX 200.25
				RHandleY -0.0755317509
				LHandleX 199.75
				LHandleY 0.0755317509
				CurveMode hermite
				CurveOrder linear
				End
			Uncollapsed
			End
		Channel position/y
			Extrapolation linear
			Value 0
			Size 6
			KeyVersion 2
			Key 0
				Frame 1
				Value -459
				RHandleX 8
				RHandleY -459
				LHandleX -6
				LHandleY -459
				CurveMode hermite
				CurveOrder linear
				End
			Key 1
				Frame 22
				Value 222.919006
				RHandleX 22.25
				RHandleY 222.880005
				LHandleX 21.75
				LHandleY 222.958008
				CurveMode hermite
				CurveOrder cubic
				RightAutomaticSlope no
				LeftAutomaticSlope no
				TangentMode manual
				End
			Key 2
				Frame 94
				Value -227
				RHandleX 94.25
				RHandleY -227.614304
				LHandleX 93.75
				LHandleY -226.385696
				CurveMode hermite
				CurveOrder constant
				End
			Key 3
				Frame 117
				Value 1.23907006
				RHandleX 117.25
				RHandleY 4.76008224
				LHandleX 116.75
				LHandleY -2.28194237
				CurveMode natural
				CurveOrder cubic
				RightAutomaticSlope no
				TangentMode manual
				End
			Key 4
				Frame 149
				Value 258.239014
				RHandleX 166
				RHandleY 257.985229
				LHandleX 138.333328
				LHandleY 258.398254
				CurveMode hermite
				CurveOrder cubic
				TangentMode smooth
				End
			Key 5
				Frame 200
				Value 0
				RHandleX 200.25
				RHandleY -0.0755317509
				LHandleX 199.75
				LHandleY 0.0755317509
				CurveMode hermite
				CurveOrder cubic
				RightAutomaticSlope no
				LeftAutomaticSlope no
				TangentMode manual
				End
			Uncollapsed
			End
		Channel position/z
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		Channel speed
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		Channel rotation/x
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		Channel rotation/y
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		Channel rotation/z
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		Channel scaling/x
			Extrapolation constant
			Value 100
			Uncollapsed
			End
		Channel scaling/y
			Extrapolation constant
			Value 100
			Uncollapsed
			End
		Channel scaling/z
			Extrapolation constant
			Value 100
			Uncollapsed
			End
		Channel shearing/x
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		Channel shearing/y
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		Channel shearing/z
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		Channel centre/x
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		Channel centre/y
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		Channel centre/z
			Extrapolation constant
			Value 0
			Uncollapsed
			End
		ChannelEnd
		Path position
			Dimension 3
			Closed no
			Size 0
			End

		MBlur yes
		Global no
		LookatNode -1
		Orientation 2
		RigSelection 0
		AutoScale 0
	}
End
ConcreteEnd

#
# outputs
#
CurrentOutputIdx 0
NumberOfOutputs 1
	Index 0
		Uuid 		"7339deb4-8189-458f-80ba-655bb67e6558"
		Name 		"complete_scene"
		Active yes
		CompleteScene yes
		AntiAliasing yes
		UseGMask yes
		MotionBlur yes
		DOF yes
		Camera 1000000
		Light -1
		OutputType 0
		Transparency yes
		UseEmissive yes
		UseAmbient yes
		MatteBackColor 1
		MediaMatteIdx 1
		ZDepthThreshold 0
		BilateralFilter 0
		MaxZDepth 100
		OutputMode 0
		GMaskBlendType 0
		BackgroundMode 0
		ShadowMode 2
		GMaskTransparency 0
		GMaskBlending 1
		GMaskBlendModel 0
		GMaskCorrelation 0
		BackgroundColor 0 0 0 1
	End
End

#
# layers
#
ActionLayerFileVersion 1.5
CreationDate Mon May 16 10:00:56 2011

LayerCount 0
ProxyMode PROXY_OFF

LayerEnd

#
# multitracks
#
ActionMTFileVersion 1.5
CreationDate Mon May 16 10:00:56 2011


MultiTrackEnd

#
# drawing order
#
DrawingOrderFileVersion 1.0
CreationDate Mon May 16 10:00:56 2011

LookupTableFrame 1
	LookupTableGroup 0
		LookupTableNPath 1
			OutputsSize 1
				OutputIndex 0
				ObjectColor 0
				End
			End
	LookupTableGroup 1
		LookupTableNPath 2
			OutputsSize 0
			End
	LookupTableGroup 2
		LookupTableNPath 0
			OutputsSize 0
			End
	LookupTableGroup 3
		LookupTableNPath 3
			OutputsSize 1
				OutputIndex 0
				ObjectColor 0
				End
			End
LookupAutoKey no
DrawingOrderEnd
